from __future__ import annotations

from elementary_common import concept, ref

# 초5-6 전체 4개 영역 미시 concept.
# 근거: 별책8 인쇄 p.25~32 (PDF p.31~38)의 성취기준·해설·적용 시 고려 사항·용어와 기호.

GRADE = "초5-6"


def num(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "수와 연산", unit, ctype, sdef, refs, **kw)


def pat(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "변화와 관계", unit, ctype, sdef, refs, **kw)


def geo(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "도형과 측정", unit, ctype, sdef, refs, **kw)


def dat(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "자료와 가능성", unit, ctype, sdef, refs, **kw)


def std(page, code, summary):
    return ref(f"printed p. {page}; [{code}]", "achievement_standard", summary)


def note(page, summary):
    return ref(f"printed p. {page} 성취기준 해설", "achievement_standard_note", summary)


def tnote(page, summary):
    return ref(f"printed p. {page} 적용 시 고려 사항", "teaching_note", summary)


def term(page, name):
    return ref(f"printed p. {page} 용어와 기호", "term_list", f"용어 목록의 {name}")


CONCEPTS = [
    # ---------- 수와 연산: 자연수의 혼합 계산 ----------
    num("e56_num_mixed_order", "혼합 계산의 계산 순서", "자연수의 혼합 계산", "property",
        "덧셈, 뺄셈, 곱셈, 나눗셈의 혼합 계산에서 계산하는 순서.",
        [std(25, "6수01-01", "혼합 계산에서 계산하는 순서를 안다는 진술")]),
    num("e56_num_mixed_calc", "자연수의 혼합 계산하기", "자연수의 혼합 계산", "procedure",
        "계산 순서에 따라 혼합 계산을 하는 활동.",
        [std(25, "6수01-01", "혼합 계산을 할 수 있다는 진술")],
        notes="계산 순서에 중점을 두고 지나치게 복잡한 혼합 계산은 다루지 않는다(printed p. 26)."),
    # ---------- 수와 연산: 수의 범위와 올림, 버림, 반올림 ----------
    num("e56_num_range_terms", "이상·이하·초과·미만", "수의 범위와 올림, 버림, 반올림", "term",
        "수의 범위를 나타내는 공식 용어.",
        [term(26, "이상, 이하, 초과, 미만"), std(25, "6수01-02", "이상, 이하, 초과, 미만의 의미와 쓰임을 안다는 진술")],
        aliases=["이상", "이하", "초과", "미만"]),
    num("e56_num_range_express", "수의 범위 나타내기", "수의 범위와 올림, 버림, 반올림", "procedure",
        "이상, 이하, 초과, 미만을 활용하여 수의 범위를 나타내는 활동.",
        [std(25, "6수01-02", "이를 활용하여 수의 범위를 나타낼 수 있다는 진술")]),
    num("e56_num_rounding_terms", "올림·버림·반올림", "수의 범위와 올림, 버림, 반올림", "term",
        "어림값을 구하기 위한 방법을 가리키는 공식 용어.",
        [term(26, "올림, 버림, 반올림"), std(25, "6수01-03", "올림, 버림, 반올림의 의미와 필요성을 안다는 진술")],
        aliases=["올림", "버림", "반올림"]),
    num("e56_num_estimate_value", "어림값 구하기", "수의 범위와 올림, 버림, 반올림", "procedure",
        "올림, 버림, 반올림으로 어림값을 구하고 실생활에 활용하는 활동.",
        [std(25, "6수01-03", "어림값을 구하는 방법으로 알고 실생활에 활용한다는 진술"),
         tnote(26, "측정 상황 등 어림이 필요한 실생활 사례를 통하여 의미를 알게 한다")]),
    # ---------- 수와 연산: 약수와 배수 ----------
    num("e56_num_divisor", "약수", "약수와 배수", "core_concept",
        "어떤 수를 나누어떨어지게 하는 수.",
        [term(26, "약수"), std(25, "6수01-04", "약수, 공약수, 최대공약수를 이해하고 구할 수 있다는 진술")]),
    num("e56_num_multiple", "배수", "약수와 배수", "core_concept",
        "어떤 수를 1배, 2배, 3배 한 수.",
        [term(26, "배수"), std(25, "6수01-05", "배수, 공배수, 최소공배수를 이해하고 구할 수 있다는 진술")]),
    num("e56_num_common_divisor", "공약수와 최대공약수", "약수와 배수", "sub_concept",
        "두 수의 공통된 약수와 그중 가장 큰 수.",
        [term(26, "공약수, 최대공약수"), std(25, "6수01-04", "공약수, 최대공약수를 이해하고 구할 수 있다는 진술")],
        aliases=["공약수", "최대공약수"]),
    num("e56_num_common_multiple", "공배수와 최소공배수", "약수와 배수", "sub_concept",
        "두 수의 공통된 배수와 그중 가장 작은 수.",
        [term(26, "공배수, 최소공배수"), std(25, "6수01-05", "공배수, 최소공배수를 이해하고 구할 수 있다는 진술")],
        aliases=["공배수", "최소공배수"]),
    num("e56_num_gcd_lcm_find", "나열하여 최대공약수·최소공배수 구하기", "약수와 배수", "procedure",
        "약수와 배수를 각각 나열하여 공통된 약수와 배수를 찾는 활동.",
        [tnote(26, "약수와 배수를 각각 나열하여 공통된 약수와 배수를 찾는 방법으로 의미를 이해하게 한다")],
        notes="평가에서 소인수의 곱으로 나타내어 구하는 방법은 다루지 않는다(printed p. 26)."),
    num("e56_num_divisor_multiple_rel", "약수와 배수의 관계", "약수와 배수", "property",
        "약수와 배수 사이의 관계.",
        [tnote(26, "약수와 배수를 학습하는 과정에서 약수와 배수의 관계를 이해하게 한다")]),
    # ---------- 수와 연산: 분수의 덧셈과 뺄셈 ----------
    num("e56_num_equal_fraction", "크기가 같은 분수", "분수의 덧셈과 뺄셈", "sub_concept",
        "구체물이나 그림으로 만들어 이해하는 크기가 같은 분수.",
        [std(25, "6수01-06", "크기가 같은 분수를 만드는 방법을 이해한다는 진술"),
         tnote(26, "구체물이나 그림으로 크기가 같은 분수를 만든 후 분모끼리, 분자끼리 비교하는 활동을 한다")]),
    num("e56_num_reduce", "약분", "분수의 덧셈과 뺄셈", "term",
        "분수를 간단히 하는 방법을 가리키는 공식 용어.",
        [term(26, "약분"), std(25, "6수01-06", "분수를 약분, 통분할 수 있다는 진술")]),
    num("e56_num_common_denominator", "통분", "분수의 덧셈과 뺄셈", "term",
        "분모를 같게 만드는 방법을 가리키는 공식 용어.",
        [term(26, "통분"), std(25, "6수01-06", "분수를 약분, 통분할 수 있다는 진술")],
        notes="공통분모로 최소공배수뿐 아니라 분모의 곱과 같은 공배수도 이용하게 할 수 있다(printed p. 26)."),
    num("e56_num_irreducible", "기약분수", "분수의 덧셈과 뺄셈", "term",
        "더 이상 약분되지 않는 분수를 가리키는 공식 용어.",
        [term(26, "기약분수")],
        notes="기약분수로 나타낼 것을 요구하지 않으면 기약분수가 아닌 결과도 허용한다(printed p. 26)."),
    num("e56_num_diff_denom_compare", "분모가 다른 분수의 크기 비교", "분수의 덧셈과 뺄셈", "procedure",
        "분모가 다른 분수의 크기를 비교하고 방법을 설명하는 활동.",
        [std(25, "6수01-07", "분모가 다른 분수의 크기를 비교하고 그 방법을 설명한다는 진술"),
         tnote(26, "수 감각을 이용하여 추론하고 토론하는 활동을 하게 한다")]),
    num("e56_num_diff_denom_addsub", "분모가 다른 분수의 덧셈과 뺄셈", "분수의 덧셈과 뺄셈", "procedure",
        "분모가 다른 분수의 덧셈과 뺄셈의 계산 원리를 탐구하고 계산하는 활동.",
        [std(25, "6수01-08", "계산 원리를 탐구하고 그 계산을 할 수 있다는 진술")]),
    # ---------- 수와 연산: 분수의 곱셈과 나눗셈 ----------
    num("e56_num_fraction_mul", "분수의 곱셈", "분수의 곱셈과 나눗셈", "procedure",
        "분수의 곱셈의 계산 원리를 탐구하고 계산하는 활동.",
        [std(25, "6수01-09", "계산 원리를 탐구하고 그 계산을 할 수 있다는 진술")],
        notes="계산 원리를 탐구하여 이해하는 수준에서 다룬다(printed p. 26)."),
    num("e56_num_quotient_fraction", "나눗셈의 몫을 분수로 나타내기", "분수의 곱셈과 나눗셈", "procedure",
        "'(자연수)÷(자연수)'에서 나눗셈의 몫을 분수로 나타내는 활동.",
        [std(25, "6수01-10", "몫을 분수로 나타낼 수 있다는 진술")]),
    num("e56_num_fraction_div", "분수의 나눗셈", "분수의 곱셈과 나눗셈", "procedure",
        "분수의 나눗셈의 계산 원리를 탐구하고 계산하는 활동.",
        [std(25, "6수01-11", "계산 원리를 탐구하고 그 계산을 할 수 있다는 진술"),
         note(26, "(분수)÷(자연수), (자연수)÷(분수), (분수)÷(분수)를 다룬다")]),
    # ---------- 수와 연산: 분수와 소수의 관계, 소수의 곱셈과 나눗셈 ----------
    num("e56_num_fraction_decimal_rel", "분수와 소수의 관계와 크기 비교", "분수와 소수의 관계", "procedure",
        "분수와 소수의 관계를 이해하고 크기를 비교하며 방법을 설명하는 활동.",
        [std(25, "6수01-12", "분수와 소수의 관계를 이해하고 크기를 비교한다는 진술")]),
    num("e56_num_decimal_mul", "소수의 곱셈", "소수의 곱셈과 나눗셈", "procedure",
        "소수의 곱셈의 계산 원리를 탐구하고 계산하는 활동.",
        [std(25, "6수01-13", "계산 원리를 탐구하고 그 계산을 할 수 있다는 진술")],
        notes="복잡한 계산은 계산기를 사용하게 할 수 있다(printed p. 26)."),
    num("e56_num_quotient_decimal", "나눗셈의 몫을 소수로 나타내기", "소수의 곱셈과 나눗셈", "procedure",
        "'(자연수)÷(자연수)'에서 나눗셈의 몫을 소수로 나타내는 활동.",
        [std(25, "6수01-14", "몫을 소수로 나타낼 수 있다는 진술")]),
    num("e56_num_decimal_div", "소수의 나눗셈", "소수의 곱셈과 나눗셈", "procedure",
        "소수의 나눗셈의 계산 원리를 탐구하고 계산하는 활동.",
        [std(25, "6수01-15", "계산 원리를 탐구하고 그 계산을 할 수 있다는 진술"),
         note(26, "(소수)÷(자연수), (자연수)÷(소수), (소수)÷(소수)를 다룬다")]),
    num("e56_num_estimation_need", "어림셈의 필요성과 유용성", "소수의 곱셈과 나눗셈", "property",
        "정확한 계산 대신 어림셈으로 비교가 가능한 상황 등에서 아는 어림셈의 필요성.",
        [tnote(26, "어림셈이 필요한 실생활 상황을 제시하여 어림셈의 필요성과 유용성을 알게 한다")]),
    # ---------- 변화와 관계: 대응 관계 ----------
    pat("e56_pat_correspondence", "대응 관계", "대응 관계", "core_concept",
        "한 양이 변할 때 다른 양이 그에 종속하여 변하는 관계.",
        [std(27, "6수02-01", "대응 관계를 나타낸 표에서 규칙을 찾아 설명한다는 진술")],
        notes="두 양의 변화를 함께 고려하게 하고 한 양의 변화에만 초점을 두지 않는다(printed p. 27)."),
    pat("e56_pat_corr_table_rule", "대응 관계 표에서 규칙 찾기", "대응 관계", "procedure",
        "대응 관계를 나타낸 표에서 규칙을 찾아 설명하는 활동.",
        [std(27, "6수02-01", "표에서 규칙을 찾아 설명한다는 진술")]),
    pat("e56_pat_corr_expression", "□·△를 사용하여 식으로 나타내기", "대응 관계", "procedure",
        "대응 관계를 □, △ 등을 사용하여 식으로 나타내는 활동.",
        [std(27, "6수02-01", "□, △ 등을 사용하여 식으로 나타낼 수 있다는 진술")],
        notes="덧셈식, 뺄셈식, 곱셈식, 나눗셈식 중 하나로 표현되는 간단한 경우만 다룬다(printed p. 27)."),
    # ---------- 변화와 관계: 비와 비율 ----------
    pat("e56_pat_ratio", "비", "비와 비율", "core_concept",
        "두 양의 크기를 비교하는 상황에서 두 양의 관계를 나타내는 개념.",
        [term(27, "비"), std(27, "6수02-02", "비의 개념을 이해하고 두 양의 관계를 비로 나타낸다는 진술"),
         note(27, "한 양을 기준으로 다른 양이 몇 배가 되는지 나타낼 필요성을 인식하며 비의 개념을 이해하게 한다")]),
    pat("e56_pat_base_quantity", "기준량과 비교하는 양", "비와 비율", "term",
        "비에서 기준이 되는 양과 비교하는 양.",
        [term(27, "기준량, 비교하는 양"),
         tnote(27, "비와 비율을 다룰 때 기준량과 비교하는 양을 명확하게 인식하게 한다")],
        aliases=["기준량", "비교하는 양"]),
    pat("e56_pat_colon", "비의 기호 :", "비와 비율", "term",
        "비를 나타내는 기호.",
        [term(27, ":")]),
    pat("e56_pat_ratio_express", "두 양의 관계를 비로 나타내기", "비와 비율", "procedure",
        "두 양의 관계를 비로 나타내는 활동.",
        [std(27, "6수02-02", "두 양의 관계를 비로 나타낼 수 있다는 진술")]),
    pat("e56_pat_rate", "비율", "비와 비율", "core_concept",
        "기준량에 대한 비교하는 양의 크기.",
        [term(27, "비율"), std(27, "6수02-03", "비율을 이해한다는 진술")]),
    pat("e56_pat_percent", "백분율과 기호 %", "비와 비율", "term",
        "비율을 100을 기준으로 나타낸 것과 그 기호.",
        [term(27, "백분율, %"), std(27, "6수02-03", "비율을 분수, 소수, 백분율로 나타낸다는 진술")],
        aliases=["백분율", "%"]),
    pat("e56_pat_rate_express", "비율을 분수·소수·백분율로 나타내기", "비와 비율", "procedure",
        "동일한 비율을 분수, 소수, 백분율로 다양하게 나타내는 활동.",
        [std(27, "6수02-03", "비율을 분수, 소수, 백분율로 나타낼 수 있다는 진술"),
         tnote(27, "동일한 비율을 분수, 소수, 백분율로 다양하게 나타낼 수 있음을 알게 한다")]),
    # ---------- 변화와 관계: 비례식과 비례배분 ----------
    pat("e56_pat_proportion", "비례식", "비례식과 비례배분", "core_concept",
        "두 비가 같음을 나타내는 식.",
        [term(27, "비례식"), std(27, "6수02-04", "비례식을 알고 그 성질을 이해한다는 진술")]),
    pat("e56_pat_proportion_solve", "비례식의 성질을 활용해 풀기", "비례식과 비례배분", "procedure",
        "비례식의 성질을 활용하여 간단한 비례식을 푸는 활동.",
        [std(27, "6수02-04", "성질을 활용하여 간단한 비례식을 풀 수 있다는 진술")]),
    pat("e56_pat_proportional_div", "비례배분", "비례식과 비례배분", "core_concept",
        "주어진 양을 비에 따라 나누는 것.",
        [term(27, "비례배분"), std(27, "6수02-05", "비례배분을 알고 주어진 양을 비례배분 할 수 있다는 진술")]),
    pat("e56_pat_proportional_div_do", "주어진 양을 비례배분 하기", "비례식과 비례배분", "procedure",
        "주어진 양을 비례배분 하는 활동.",
        [std(27, "6수02-05", "주어진 양을 비례배분 할 수 있다는 진술")]),
    # ---------- 도형과 측정: 합동과 대칭 ----------
    geo("e56_geo_congruence", "도형의 합동", "합동과 대칭", "core_concept",
        "모양과 크기가 같아 포개어지는 두 도형의 관계.",
        [term(29, "합동"), std(28, "6수03-01", "도형의 합동을 이해한다는 진술")],
        notes="무늬 찾기, 종이 겹쳐 오리기, 도장 찍기, 데칼코마니 등 조작 활동으로 의미를 알게 한다(printed p. 30)."),
    geo("e56_geo_correspondence", "대응점·대응변·대응각", "합동과 대칭", "term",
        "합동인 두 도형에서 서로 대응하는 구성 요소.",
        [term(29, "대응점, 대응변, 대응각"),
         note(29, "합동인 두 도형에서 대응점, 대응변, 대응각을 각각 찾게 한다")],
        aliases=["대응점", "대응변", "대응각"]),
    geo("e56_geo_congruence_property", "합동인 도형의 성질 탐구하기", "합동과 대칭", "procedure",
        "대응변의 길이와 대응각의 크기를 비교하여 합동인 도형의 성질을 탐구하고 설명하는 활동.",
        [std(28, "6수03-01", "합동인 도형의 성질을 탐구하고 설명할 수 있다는 진술"),
         note(29, "대응변의 길이와 대응각의 크기를 비교하는 활동을 통해 성질을 탐구하게 한다")]),
    geo("e56_geo_line_symmetry", "선대칭도형", "합동과 대칭", "core_concept",
        "한 직선을 따라 접어서 완전히 겹치는 도형.",
        [term(29, "선대칭도형"), std(28, "6수03-02", "선대칭도형과 점대칭도형을 이해하고 그린다는 진술")]),
    geo("e56_geo_point_symmetry", "점대칭도형", "합동과 대칭", "core_concept",
        "한 점을 중심으로 180도 돌렸을 때 완전히 겹치는 도형.",
        [term(29, "점대칭도형"), std(28, "6수03-02", "선대칭도형과 점대칭도형을 이해하고 그린다는 진술")]),
    geo("e56_geo_symmetry_axis", "대칭축과 대칭의 중심", "합동과 대칭", "term",
        "선대칭도형의 축과 점대칭도형의 중심.",
        [term(29, "대칭축, 대칭의 중심")],
        aliases=["대칭축", "대칭의 중심"]),
    geo("e56_geo_symmetry_draw", "선대칭·점대칭도형 그리기", "합동과 대칭", "procedure",
        "실생활과 연결하여 선대칭도형과 점대칭도형을 그리는 활동.",
        [std(28, "6수03-02", "선대칭도형과 점대칭도형을 이해하고 그릴 수 있다는 진술")],
        notes="평가에서 모눈종이, 점판, 공학 도구 등을 이용하여 쉽게 그릴 수 있게 한다(printed p. 30)."),
    # ---------- 도형과 측정: 직육면체와 정육면체 ----------
    geo("e56_geo_cuboid", "직육면체", "직육면체와 정육면체", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "직육면체"), std(28, "6수03-03", "직육면체와 정육면체를 이해한다는 진술")]),
    geo("e56_geo_cube", "정육면체", "직육면체와 정육면체", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "정육면체"), std(28, "6수03-03", "직육면체와 정육면체를 이해한다는 진술")]),
    geo("e56_geo_solid_elements", "면·모서리·밑면·옆면", "직육면체와 정육면체", "term",
        "입체도형의 구성 요소를 가리키는 공식 용어.",
        [term(29, "면, 모서리, 밑면, 옆면")],
        aliases=["면", "모서리", "밑면", "옆면"]),
    geo("e56_geo_cuboid_property", "직육면체·정육면체의 구성 요소와 성질 탐구하기", "직육면체와 정육면체", "procedure",
        "직육면체와 정육면체의 구성 요소와 성질을 탐구하고 설명하는 활동.",
        [std(28, "6수03-03", "구성 요소와 성질을 탐구하고 설명할 수 있다는 진술")]),
    geo("e56_geo_sketch", "겨냥도", "직육면체와 정육면체", "term",
        "입체도형의 모양을 잘 알 수 있도록 나타낸 그림.",
        [term(29, "겨냥도"), std(28, "6수03-04", "겨냥도와 전개도를 그릴 수 있다는 진술")]),
    geo("e56_geo_net", "전개도", "직육면체와 정육면체", "term",
        "입체도형을 펼쳐서 평면에 나타낸 그림.",
        [term(29, "전개도"), std(28, "6수03-04", "겨냥도와 전개도를 그릴 수 있다는 진술")]),
    geo("e56_geo_net_draw", "직육면체·정육면체의 겨냥도와 전개도 그리기", "직육면체와 정육면체", "procedure",
        "직육면체와 정육면체의 겨냥도와 전개도를 그리는 활동.",
        [std(28, "6수03-04", "겨냥도와 전개도를 그릴 수 있다는 진술")],
        notes="전개도 평가는 전개도가 될 수 있는 것과 될 수 없는 것을 구별하는 데 중점을 둔다(printed p. 30)."),
    # ---------- 도형과 측정: 각기둥과 각뿔 ----------
    geo("e56_geo_prism", "각기둥", "각기둥과 각뿔", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "각기둥"), std(28, "6수03-05", "각기둥과 각뿔을 이해한다는 진술")]),
    geo("e56_geo_pyramid", "각뿔", "각기둥과 각뿔", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "각뿔"), std(28, "6수03-05", "각기둥과 각뿔을 이해한다는 진술")]),
    geo("e56_geo_prism_property", "각기둥·각뿔의 구성 요소와 성질 탐구하기", "각기둥과 각뿔", "procedure",
        "각기둥과 각뿔의 구성 요소와 성질을 탐구하고 설명하는 활동.",
        [std(28, "6수03-05", "구성 요소와 성질을 탐구하고 설명할 수 있다는 진술")]),
    geo("e56_geo_prism_net", "각기둥의 전개도 그리기", "각기둥과 각뿔", "procedure",
        "각기둥의 전개도를 그리는 활동.",
        [std(28, "6수03-06", "각기둥의 전개도를 그릴 수 있다는 진술")],
        notes="각기둥의 전개도는 간단한 형태만 다루고, 각뿔과 원뿔의 전개도는 다루지 않는다(printed p. 30)."),
    # ---------- 도형과 측정: 원기둥, 원뿔, 구 ----------
    geo("e56_geo_cylinder", "원기둥", "원기둥, 원뿔, 구", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "원기둥"), std(28, "6수03-07", "원기둥, 원뿔, 구를 이해한다는 진술")]),
    geo("e56_geo_cone", "원뿔", "원기둥, 원뿔, 구", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "원뿔"), std(28, "6수03-07", "원기둥, 원뿔, 구를 이해한다는 진술")]),
    geo("e56_geo_sphere", "구", "원기둥, 원뿔, 구", "core_concept",
        "구성 요소와 성질을 탐구하는 입체도형.",
        [term(29, "구"), std(28, "6수03-07", "원기둥, 원뿔, 구를 이해한다는 진술")]),
    geo("e56_geo_generatrix", "모선", "원기둥, 원뿔, 구", "term",
        "원기둥과 원뿔의 구성 요소를 가리키는 공식 용어.",
        [term(29, "모선")]),
    geo("e56_geo_round_property", "원기둥·원뿔·구의 구성 요소와 성질 탐구하기", "원기둥, 원뿔, 구", "procedure",
        "원기둥, 원뿔, 구의 구성 요소와 성질을 탐구하고 설명하는 활동.",
        [std(28, "6수03-07", "구성 요소와 성질을 탐구하고 설명할 수 있다는 진술")]),
    geo("e56_geo_cylinder_net", "원기둥의 전개도 그리기", "원기둥, 원뿔, 구", "procedure",
        "원기둥의 전개도를 그리는 활동.",
        [std(28, "6수03-08", "원기둥의 전개도를 그릴 수 있다는 진술")]),
    geo("e56_geo_rotate", "평면도형을 돌려 입체도형 만들기", "원기둥, 원뿔, 구", "procedure",
        "한 직선을 중심으로 직사각형, 직각삼각형, 반원을 돌려 원기둥, 원뿔, 구를 만드는 활동.",
        [tnote(30, "한 직선을 중심으로 직사각형, 직각삼각형, 반원을 돌리는 활동으로 원기둥, 원뿔, 구를 만들어 보게 한다")]),
    # ---------- 도형과 측정: 입체도형의 공간 감각 ----------
    geo("e56_geo_block_count", "쌓기나무 개수 구하기", "입체도형의 공간 감각", "procedure",
        "쌓기나무로 만든 입체도형을 보고 사용된 쌓기나무의 개수를 구하는 활동.",
        [std(28, "6수03-09", "사용된 쌓기나무의 개수를 구할 수 있다는 진술")]),
    geo("e56_geo_views", "위·앞·옆에서 본 모양 표현하고 추측하기", "입체도형의 공간 감각", "procedure",
        "입체도형의 위, 앞, 옆에서 본 모양을 표현하고 그 표현으로 전체 모양을 추측하는 활동.",
        [std(28, "6수03-10", "위, 앞, 옆에서 본 모양을 표현하고 모양을 추측할 수 있다는 진술"),
         note(29, "위, 앞, 옆에서 본 모양으로 전체 모양을 추측하고 추론 과정을 설명하게 한다")]),
    # ---------- 도형과 측정: 다각형의 둘레와 넓이 ----------
    geo("e56_meas_perimeter", "평면도형의 둘레", "다각형의 둘레와 넓이", "core_concept",
        "평면도형의 가장자리 길이.",
        [std(29, "6수03-11", "평면도형의 둘레를 이해하고 기본적인 평면도형의 둘레를 구한다는 진술")]),
    geo("e56_meas_area_units", "넓이 단위 1cm²·1m²·1km²", "다각형의 둘레와 넓이", "term",
        "넓이의 표준 단위와 그 관계.",
        [term(29, "cm², m², km²"), std(29, "6수03-12", "넓이 단위를 알며 그 관계를 이해한다는 진술")],
        notes="1cm²와 1km² 사이의 단위 환산은 다루지 않는다(printed p. 30)."),
    geo("e56_meas_area_meaning", "넓이는 단위넓이의 몇 배", "다각형의 둘레와 넓이", "property",
        "도형의 넓이는 1cm²인 정사각형의 몇 배인지를 구하는 것임.",
        [tnote(30, "도형의 넓이는 1cm²인 정사각형의 몇 배인지를 구하는 것임을 이해하게 한다")]),
    geo("e56_meas_rect_area", "직사각형·정사각형의 넓이 구하기", "다각형의 둘레와 넓이", "procedure",
        "직사각형과 정사각형의 넓이를 구하는 방법을 이해하고 구하는 활동.",
        [std(29, "6수03-13", "넓이를 구하는 방법을 이해하고 이를 구할 수 있다는 진술")]),
    geo("e56_meas_dimension_terms", "가로·세로·밑변·높이", "다각형의 둘레와 넓이", "term",
        "넓이 구하기에 쓰는 길이 요소를 가리키는 공식 용어.",
        [term(29, "가로, 세로, 밑변, 높이")],
        aliases=["가로", "세로", "밑변", "높이"]),
    geo("e56_meas_polygon_area", "여러 가지 평면도형의 넓이 방법 추론하기", "다각형의 둘레와 넓이", "procedure",
        "평행사변형, 삼각형, 사다리꼴, 마름모의 넓이를 구하는 방법을 다양하게 추론하고 문제를 해결하는 활동.",
        [std(29, "6수03-14", "넓이를 구하는 방법을 다양하게 추론하고 문제를 해결한다는 진술"),
         tnote(30, "도형의 변형을 이용하여 넓이를 구하는 여러 가지 방법을 추론하게 한다")],
        notes="삼각형의 넓이에서 높이가 외부에 있는 경우도 다룬다(printed p. 30)."),
    # ---------- 도형과 측정: 원주율과 원의 넓이 ----------
    geo("e56_meas_circumference", "원주", "원주율과 원의 넓이", "term",
        "원의 둘레를 가리키는 공식 용어.",
        [term(29, "원주"), std(29, "6수03-15", "원주와 지름을 측정하는 활동이라는 진술")]),
    geo("e56_meas_pi", "원주율", "원주율과 원의 넓이", "core_concept",
        "원주를 지름으로 나눈 일정한 값.",
        [term(29, "원주율"), std(29, "6수03-15", "원주율이 일정한 값임을 알고 근삿값을 사용한다는 진술"),
         note(29, "(원주)÷(지름)의 값이 모든 원에서 일정함을 이해하게 하고 근삿값으로 3.14를 사용하게 한다")]),
    geo("e56_meas_circle_area", "원주와 원의 넓이 구하기", "원주율과 원의 넓이", "procedure",
        "원주와 원의 넓이를 구하는 방법을 이해하고 구하는 활동.",
        [std(29, "6수03-16", "원주와 원의 넓이를 구하는 방법을 이해하고 구한다는 진술"),
         note(29, "직사각형의 넓이를 구하는 방법을 이용하여 원의 넓이 구하는 방법을 이해하게 한다")]),
    # ---------- 도형과 측정: 입체도형의 겉넓이와 부피 ----------
    geo("e56_meas_surface_area", "직육면체·정육면체의 겉넓이 구하기", "입체도형의 겉넓이와 부피", "procedure",
        "직육면체와 정육면체의 겉넓이를 구하는 방법을 이해하고 구하는 활동.",
        [std(29, "6수03-17", "겉넓이를 구하는 방법을 이해하고 구할 수 있다는 진술")]),
    geo("e56_meas_volume_units", "부피 단위 1cm³·1m³", "입체도형의 겉넓이와 부피", "term",
        "부피의 표준 단위와 그 관계.",
        [term(29, "cm³, m³"), std(29, "6수03-18", "부피 단위를 알며 그 관계를 이해한다는 진술")]),
    geo("e56_meas_volume", "직육면체·정육면체의 부피 구하기", "입체도형의 겉넓이와 부피", "procedure",
        "직육면체와 정육면체의 부피를 구하는 방법을 이해하고 구하는 활동.",
        [std(29, "6수03-19", "부피를 구하는 방법을 이해하고 구할 수 있다는 진술")],
        notes="겉넓이와 부피를 구하는 방법을 다양하게 추론하고 설명하게 할 수 있다(printed p. 30)."),
    # ---------- 자료와 가능성: 자료의 수집과 정리 ----------
    dat("e56_data_mean", "평균", "자료의 수집과 정리", "core_concept",
        "집단의 자료를 대표하는 값.",
        [term(31, "평균"), std(31, "6수04-01", "평균의 의미를 안다는 진술"),
         note(31, "평균은 집단의 자료를 대표하는 값임을 이해하게 한다")]),
    dat("e56_data_mean_calc", "평균 구하고 해석하기", "자료의 수집과 정리", "procedure",
        "자료를 수집하여 평균을 구하고 해석하는 활동.",
        [std(31, "6수04-01", "자료를 수집하여 평균을 구하고 해석할 수 있다는 진술")],
        notes="구하는 방법뿐 아니라 의미를 직관적으로 파악하게 한다(printed p. 32)."),
    dat("e56_data_band_graph", "띠그래프", "자료의 수집과 정리", "term",
        "전체에 대한 각 부분의 비율을 나타내는 그래프.",
        [term(31, "띠그래프"), std(31, "6수04-02", "띠그래프나 원그래프로 나타내고 해석한다는 진술")]),
    dat("e56_data_pie_graph", "원그래프", "자료의 수집과 정리", "term",
        "전체에 대한 각 부분의 비율을 원으로 나타내는 그래프.",
        [term(31, "원그래프"), std(31, "6수04-02", "띠그래프나 원그래프로 나타내고 해석한다는 진술")],
        notes="원그래프를 그릴 때는 눈금이 표시된 원을 사용하게 한다(printed p. 32)."),
    dat("e56_data_ratio_graph_draw", "띠그래프·원그래프로 나타내고 해석하기", "자료의 수집과 정리", "procedure",
        "자료를 수집하여 띠그래프나 원그래프로 나타내고 해석하는 활동.",
        [std(31, "6수04-02", "띠그래프나 원그래프로 나타내고 해석할 수 있다는 진술"),
         tnote(32, "전체에 대한 각 부분의 비율을 비교하는 문제 상황으로 필요성을 인식하게 한다")]),
    dat("e56_data_inquiry", "탐구 문제 설정과 통계적 문제해결", "자료의 수집과 정리", "procedure",
        "탐구 문제를 설정하고 자료를 수집, 정리하여 적절한 그래프로 나타내고 해석하는 일련의 과정.",
        [std(31, "6수04-03", "탐구 문제를 설정하고 적절한 그래프로 나타내고 해석한다는 진술"),
         note(31, "막대·꺾은선·띠·원그래프 중 적절한 그래프로 나타내는 과정을 직접 경험하게 한다")]),
    # ---------- 자료와 가능성: 가능성 ----------
    dat("e56_data_possibility", "가능성", "가능성", "core_concept",
        "사건이 일어날 가능성.",
        [term(31, "가능성"), std(31, "6수04-04", "사건이 일어날 가능성을 말로 표현하고 비교한다는 진술")]),
    dat("e56_data_possibility_words", "가능성을 말로 표현하고 비교하기", "가능성", "procedure",
        "'확실하다', '불가능하다', '반반이다' 등의 표현으로 가능성을 나타내고 크기를 비교하는 활동.",
        [std(31, "6수04-04", "가능성을 말로 표현하고 비교할 수 있다는 진술"),
         note(31, "'확실하다', '불가능하다', '~일 것 같다', '반반이다' 등 다양한 표현을 이해하고 크기를 비교하게 한다")]),
    dat("e56_data_possibility_number", "가능성을 수로 나타내기", "가능성", "procedure",
        "간단한 사건의 가능성을 0, 1/2, 1 등의 수로 표현하는 활동.",
        [std(31, "6수04-05", "사건이 일어날 가능성을 수로 나타낼 수 있다는 진술"),
         note(31, "가능성이 직관적으로 파악되는 간단한 사건의 가능성을 0, 1/2, 1 등의 수로 표현하게 한다")]),
    dat("e56_data_possibility_judge", "자료로 가능성 예상하고 판단하기", "가능성", "procedure",
        "실험 결과를 나타낸 표나 그래프로 가능성을 비교·예상하고 적절한 판단을 내리는 활동.",
        [std(31, "6수04-06", "자료를 이용하여 가능성을 예상하고 판단을 내릴 수 있다는 진술"),
         note(31, "제비뽑기, 동전 던지기 등 간단한 실험 결과의 표나 그래프로 가능성을 비교하고 예상하게 한다")]),
    dat("e56_data_distortion", "정보 왜곡 여부 비판적으로 판단하기", "자료의 수집과 정리", "procedure",
        "그래프가 정보를 왜곡하는 오류를 포함하는지 비판적으로 판단하는 활동.",
        [tnote(32, "정보를 왜곡하는 오류가 포함되어 있지 않은지 비판적으로 판단하게 할 수 있다")]),
]

EDGE_DEFS = [
    # 수와 연산
    ("e56_num_mixed_order", "e56_num_mixed_calc", "prerequisite_for", "high", "printed p. 25; [6수01-01]", "계산 순서를 알고 혼합 계산을 한다는 진술 구조", ""),
    ("e34_num_div1_calc", "e56_num_mixed_calc", "prerequisite_for", "medium", "printed p. 17, 25", "사칙연산 각각의 계산에서 혼합 계산으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_num_range_terms", "e56_num_range_express", "used_in", "high", "printed p. 25; [6수01-02]", "이상, 이하, 초과, 미만을 활용하여 수의 범위를 나타낸다", ""),
    ("e56_num_rounding_terms", "e56_num_estimate_value", "used_in", "high", "printed p. 25; [6수01-03]", "올림, 버림, 반올림으로 어림값을 구한다", ""),
    ("e34_num_estimation", "e56_num_estimate_value", "prerequisite_for", "medium", "printed p. 17, 25", "어림셈 경험에서 올림·버림·반올림의 형식적 방법으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_num_divisor", "e56_num_common_divisor", "contains", "high", "printed p. 25; [6수01-04]", "공약수와 최대공약수는 약수 개념에 기초한다", ""),
    ("e56_num_multiple", "e56_num_common_multiple", "contains", "high", "printed p. 25; [6수01-05]", "공배수와 최소공배수는 배수 개념에 기초한다", ""),
    ("e56_num_divisor", "e56_num_divisor_multiple_rel", "used_in", "high", "printed p. 26 적용 시 고려 사항", "약수와 배수의 관계를 이해하게 한다", ""),
    ("e56_num_multiple", "e56_num_divisor_multiple_rel", "used_in", "high", "printed p. 26 적용 시 고려 사항", "약수와 배수의 관계를 이해하게 한다", ""),
    ("e56_num_common_divisor", "e56_num_gcd_lcm_find", "used_in", "high", "printed p. 26 적용 시 고려 사항", "나열하여 공통된 약수를 찾는 방법으로 의미를 이해하게 한다", ""),
    ("e56_num_common_multiple", "e56_num_gcd_lcm_find", "used_in", "high", "printed p. 26 적용 시 고려 사항", "나열하여 공통된 배수를 찾는 방법으로 의미를 이해하게 한다", ""),
    ("e34_num_div", "e56_num_divisor", "prerequisite_for", "medium", "printed p. 17, 25", "나눗셈과 나누어떨어짐 이해가 약수 이해로 이어진다", "학년군 사이 확장에서 추론한 관계다."),
    ("e34_num_mul_multi", "e56_num_multiple", "prerequisite_for", "medium", "printed p. 17, 25", "곱셈 이해가 배수 이해로 이어진다", "학년군 사이 확장에서 추론한 관계다."),
    ("e56_num_equal_fraction", "e56_num_reduce", "prerequisite_for", "high", "printed p. 25; [6수01-06]", "크기가 같은 분수를 만드는 방법을 이해하고 약분, 통분한다는 진술 구조", ""),
    ("e56_num_equal_fraction", "e56_num_common_denominator", "prerequisite_for", "high", "printed p. 25; [6수01-06]", "크기가 같은 분수를 만드는 방법을 이해하고 약분, 통분한다는 진술 구조", ""),
    ("e56_num_common_multiple", "e56_num_common_denominator", "used_in", "high", "printed p. 26 적용 시 고려 사항", "통분의 공통분모로 최소공배수와 공배수를 이용하게 한다", ""),
    ("e56_num_reduce", "e56_num_irreducible", "related_to", "high", "printed p. 26 용어와 기호", "약분과 기약분수가 같은 용어 목록에서 도입된다", ""),
    ("e56_num_common_denominator", "e56_num_diff_denom_compare", "prerequisite_for", "high", "printed p. 25; [6수01-06]~[6수01-07]", "통분을 바탕으로 분모가 다른 분수의 크기를 비교하는 구성", ""),
    ("e56_num_common_denominator", "e56_num_diff_denom_addsub", "prerequisite_for", "high", "printed p. 25; [6수01-06]~[6수01-08]", "통분을 바탕으로 분모가 다른 분수의 덧셈과 뺄셈을 다루는 구성", ""),
    ("e34_num_fraction_addsub", "e56_num_diff_denom_addsub", "prerequisite_for", "medium", "printed p. 18, 25", "분모가 같은 분수의 덧셈·뺄셈에서 분모가 다른 경우로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_num_fraction", "e56_num_fraction_mul", "prerequisite_for", "medium", "printed p. 17, 25", "분수 이해에서 분수의 곱셈으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_num_fraction_mul", "e56_num_fraction_div", "prerequisite_for", "medium", "printed p. 25; [6수01-09]~[6수01-11]", "분수의 곱셈에서 나눗셈으로 이어지는 성취기준 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e34_num_quotient", "e56_num_quotient_fraction", "used_in", "high", "printed p. 25; [6수01-10]", "나눗셈의 몫을 분수로 나타낸다", ""),
    ("e34_num_decimal", "e56_num_decimal_mul", "prerequisite_for", "medium", "printed p. 17, 25", "소수 이해에서 소수의 곱셈으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_num_decimal_mul", "e56_num_decimal_div", "prerequisite_for", "medium", "printed p. 25; [6수01-13]~[6수01-15]", "소수의 곱셈에서 나눗셈으로 이어지는 성취기준 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e34_num_fraction", "e56_num_fraction_decimal_rel", "used_in", "high", "printed p. 25; [6수01-12]", "분수와 소수의 관계를 이해하고 크기를 비교한다", ""),
    ("e34_num_decimal", "e56_num_fraction_decimal_rel", "used_in", "high", "printed p. 25; [6수01-12]", "분수와 소수의 관계를 이해하고 크기를 비교한다", ""),
    ("e56_num_estimation_need", "e56_num_decimal_mul", "related_to", "high", "printed p. 26 적용 시 고려 사항", "소수의 곱셈·나눗셈에서 어림셈이 필요한 상황을 제시한다", ""),
    # 변화와 관계
    ("e34_pat_change_rule", "e56_pat_correspondence", "prerequisite_for", "medium", "printed p. 19, 27", "변화 규칙에서 두 양의 대응 관계로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_pat_correspondence", "e56_pat_corr_table_rule", "used_in", "high", "printed p. 27; [6수02-01]", "대응 관계를 나타낸 표에서 규칙을 찾는다", ""),
    ("e56_pat_corr_table_rule", "e56_pat_corr_expression", "prerequisite_for", "high", "printed p. 27; [6수02-01]", "표에서 규칙을 찾아 식으로 나타낸다는 진술 구조", ""),
    ("e12_box_expressions", "e56_pat_corr_expression", "related_to", "medium", "printed p. 11, 27", "□를 사용한 식 경험이 □·△ 대응식 표현과 이어진다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e56_pat_ratio", "e56_pat_base_quantity", "contains", "high", "printed p. 27 적용 시 고려 사항", "비에서 기준량과 비교하는 양을 명확히 인식하게 한다", ""),
    ("e56_pat_ratio", "e56_pat_colon", "represented_by", "high", "printed p. 27 용어와 기호", "비는 기호 :로 나타낸다", ""),
    ("e56_pat_ratio", "e56_pat_ratio_express", "used_in", "high", "printed p. 27; [6수02-02]", "두 양의 관계를 비로 나타낸다", ""),
    ("e56_pat_ratio", "e56_pat_rate", "prerequisite_for", "high", "printed p. 27; [6수02-02]~[6수02-03]", "비의 개념을 바탕으로 비율을 이해하는 구성", ""),
    ("e56_pat_rate", "e56_pat_percent", "represented_by", "high", "printed p. 27; [6수02-03]", "비율을 백분율로 나타낸다", ""),
    ("e56_pat_rate", "e56_pat_rate_express", "used_in", "high", "printed p. 27; [6수02-03]", "비율을 분수, 소수, 백분율로 나타낸다", ""),
    ("e34_num_fraction", "e56_pat_rate_express", "used_in", "high", "printed p. 27; [6수02-03]", "비율을 분수로 나타낸다", ""),
    ("e34_num_decimal", "e56_pat_rate_express", "used_in", "high", "printed p. 27; [6수02-03]", "비율을 소수로 나타낸다", ""),
    ("e56_pat_ratio", "e56_pat_proportion", "prerequisite_for", "high", "printed p. 27; [6수02-02], [6수02-04]", "비를 바탕으로 비례식을 다루는 구성", ""),
    ("e56_pat_proportion", "e56_pat_proportion_solve", "used_in", "high", "printed p. 27; [6수02-04]", "비례식의 성질을 활용하여 간단한 비례식을 푼다", ""),
    ("e56_pat_ratio", "e56_pat_proportional_div", "prerequisite_for", "high", "printed p. 27; [6수02-05]", "비에 따라 주어진 양을 나누는 비례배분", ""),
    ("e56_pat_proportional_div", "e56_pat_proportional_div_do", "used_in", "high", "printed p. 27; [6수02-05]", "주어진 양을 비례배분 한다", ""),
    # 도형과 측정: 합동과 대칭
    ("e56_geo_congruence", "e56_geo_correspondence", "contains", "high", "printed p. 29 성취기준 해설", "합동인 두 도형에서 대응점, 대응변, 대응각을 찾게 한다", ""),
    ("e56_geo_correspondence", "e56_geo_congruence_property", "used_in", "high", "printed p. 29 성취기준 해설", "대응변의 길이와 대응각의 크기를 비교하여 성질을 탐구하게 한다", ""),
    ("e56_geo_congruence", "e56_geo_line_symmetry", "prerequisite_for", "medium", "printed p. 28; [6수03-01]~[6수03-02]", "합동 이해가 대칭도형 이해로 이어지는 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e56_geo_line_symmetry", "e56_geo_symmetry_axis", "contains", "high", "printed p. 29 용어와 기호", "대칭축은 선대칭도형의 구성 요소다", ""),
    ("e56_geo_point_symmetry", "e56_geo_symmetry_axis", "contains", "high", "printed p. 29 용어와 기호", "대칭의 중심은 점대칭도형의 구성 요소다", ""),
    ("e56_geo_line_symmetry", "e56_geo_symmetry_draw", "used_in", "high", "printed p. 28; [6수03-02]", "선대칭도형을 이해하고 그린다", ""),
    ("e56_geo_point_symmetry", "e56_geo_symmetry_draw", "used_in", "high", "printed p. 28; [6수03-02]", "점대칭도형을 이해하고 그린다", ""),
    ("e34_geo_flip", "e56_geo_line_symmetry", "related_to", "medium", "printed p. 20, 28", "뒤집기 경험이 선대칭 이해와 연결된다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e34_geo_turn", "e56_geo_point_symmetry", "related_to", "medium", "printed p. 20, 28", "돌리기 경험이 점대칭 이해와 연결된다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    # 도형과 측정: 입체도형
    ("e12_geo_cuboid_shape", "e56_geo_cuboid", "prerequisite_for", "medium", "printed p. 13, 28", "직육면체 모양 찾기에서 구성 요소 이해로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_geo_cuboid", "e56_geo_cube", "related_to", "high", "printed p. 28; [6수03-03]", "직육면체와 정육면체를 함께 다룬다", ""),
    ("e56_geo_cuboid", "e56_geo_solid_elements", "contains", "high", "printed p. 29 용어와 기호", "면, 모서리, 밑면, 옆면은 입체도형의 구성 요소다", ""),
    ("e56_geo_solid_elements", "e56_geo_cuboid_property", "used_in", "high", "printed p. 28; [6수03-03]", "구성 요소와 성질을 탐구하고 설명한다", ""),
    ("e56_geo_cuboid", "e56_geo_net_draw", "used_in", "high", "printed p. 28; [6수03-04]", "직육면체의 겨냥도와 전개도를 그린다", ""),
    ("e56_geo_sketch", "e56_geo_net_draw", "used_in", "high", "printed p. 28; [6수03-04]", "겨냥도를 그린다", ""),
    ("e56_geo_net", "e56_geo_net_draw", "used_in", "high", "printed p. 28; [6수03-04]", "전개도를 그린다", ""),
    ("e56_geo_prism", "e56_geo_prism_property", "used_in", "high", "printed p. 28; [6수03-05]", "각기둥의 구성 요소와 성질을 탐구한다", ""),
    ("e56_geo_pyramid", "e56_geo_prism_property", "used_in", "high", "printed p. 28; [6수03-05]", "각뿔의 구성 요소와 성질을 탐구한다", ""),
    ("e56_geo_net", "e56_geo_prism_net", "used_in", "high", "printed p. 28; [6수03-06]", "각기둥의 전개도를 그린다", ""),
    ("e56_geo_cuboid", "e56_geo_prism", "related_to", "medium", "printed p. 28; [6수03-03], [6수03-05]", "직육면체 이해가 각기둥 이해와 연결된다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e56_geo_cylinder", "e56_geo_round_property", "used_in", "high", "printed p. 28; [6수03-07]", "원기둥의 구성 요소와 성질을 탐구한다", ""),
    ("e56_geo_cone", "e56_geo_round_property", "used_in", "high", "printed p. 28; [6수03-07]", "원뿔의 구성 요소와 성질을 탐구한다", ""),
    ("e56_geo_sphere", "e56_geo_round_property", "used_in", "high", "printed p. 28; [6수03-07]", "구의 구성 요소와 성질을 탐구한다", ""),
    ("e56_geo_generatrix", "e56_geo_round_property", "used_in", "high", "printed p. 29 용어와 기호", "모선은 원기둥·원뿔의 구성 요소다", ""),
    ("e56_geo_net", "e56_geo_cylinder_net", "used_in", "high", "printed p. 28; [6수03-08]", "원기둥의 전개도를 그린다", ""),
    ("e56_geo_rotate", "e56_geo_cylinder", "used_in", "high", "printed p. 30 적용 시 고려 사항", "직사각형을 돌려 원기둥을 만들어 보게 한다", ""),
    ("e56_geo_rotate", "e56_geo_cone", "used_in", "high", "printed p. 30 적용 시 고려 사항", "직각삼각형을 돌려 원뿔을 만들어 보게 한다", ""),
    ("e56_geo_rotate", "e56_geo_sphere", "used_in", "high", "printed p. 30 적용 시 고려 사항", "반원을 돌려 구를 만들어 보게 한다", ""),
    ("e12_geo_blocks", "e56_geo_block_count", "prerequisite_for", "medium", "printed p. 13, 28", "쌓기나무 모양 만들기에서 개수 구하기·모양 추측으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_geo_block_count", "e56_geo_views", "related_to", "high", "printed p. 28; [6수03-09]~[6수03-10]", "쌓기나무 입체도형의 공간 감각 활동으로 함께 다룬다", ""),
    # 도형과 측정: 둘레·넓이·원·부피
    ("e12_meas_measure_length", "e56_meas_perimeter", "used_in", "medium", "printed p. 14, 29", "길이 측정이 둘레 구하기에 쓰인다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e56_meas_area_units", "e56_meas_rect_area", "used_in", "high", "printed p. 29; [6수03-12]~[6수03-13]", "넓이 단위를 알고 직사각형의 넓이를 구한다", ""),
    ("e56_meas_area_meaning", "e56_meas_rect_area", "used_in", "high", "printed p. 30 적용 시 고려 사항", "넓이는 1cm² 정사각형의 몇 배임을 이해하고 넓이를 구한다", ""),
    ("e56_meas_dimension_terms", "e56_meas_rect_area", "used_in", "high", "printed p. 29 용어와 기호", "가로, 세로를 사용해 직사각형의 넓이를 구한다", ""),
    ("e56_meas_rect_area", "e56_meas_polygon_area", "prerequisite_for", "high", "printed p. 29; [6수03-13]~[6수03-14]", "직사각형의 넓이를 바탕으로 여러 도형의 넓이 방법을 추론하는 구성", ""),
    ("e56_meas_dimension_terms", "e56_meas_polygon_area", "used_in", "high", "printed p. 29 용어와 기호", "밑변, 높이를 사용해 넓이 방법을 추론한다", ""),
    ("e34_geo_parallelogram", "e56_meas_polygon_area", "used_in", "high", "printed p. 29; [6수03-14]", "평행사변형의 넓이를 구하는 방법을 추론한다", ""),
    ("e34_geo_rhombus", "e56_meas_polygon_area", "used_in", "high", "printed p. 29; [6수03-14]", "마름모의 넓이를 구하는 방법을 추론한다", ""),
    ("e34_geo_circle_center", "e56_meas_pi", "related_to", "medium", "printed p. 20, 29", "원의 구성 요소 이해가 원주율 이해와 연결된다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e34_geo_diameter", "e56_meas_pi", "used_in", "high", "printed p. 29 성취기준 해설", "(원주)÷(지름)의 값으로 원주율이 일정함을 이해하게 한다", ""),
    ("e56_meas_circumference", "e56_meas_pi", "used_in", "high", "printed p. 29 성취기준 해설", "(원주)÷(지름)의 값으로 원주율이 일정함을 이해하게 한다", ""),
    ("e56_meas_pi", "e56_meas_circle_area", "prerequisite_for", "high", "printed p. 29 성취기준 해설", "지름과 원주율을 이용하면 원주를 구할 수 있음을 알게 한다", ""),
    ("e56_meas_rect_area", "e56_meas_circle_area", "used_in", "high", "printed p. 29 성취기준 해설", "직사각형의 넓이 방법을 이용하여 원의 넓이 방법을 이해하게 한다", ""),
    ("e56_geo_net_draw", "e56_meas_surface_area", "related_to", "medium", "printed p. 28~29; [6수03-04], [6수03-17]", "전개도 이해가 겉넓이 방법 추론과 연결된다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e56_meas_rect_area", "e56_meas_surface_area", "used_in", "high", "printed p. 29; [6수03-17]", "직사각형의 넓이 방법이 겉넓이 구하기에 쓰인다", ""),
    ("e56_meas_volume_units", "e56_meas_volume", "used_in", "high", "printed p. 29; [6수03-18]~[6수03-19]", "부피 단위를 알고 부피를 구한다", ""),
    # 자료와 가능성
    ("e56_data_mean", "e56_data_mean_calc", "used_in", "high", "printed p. 31; [6수04-01]", "평균의 의미를 알고 평균을 구하고 해석한다", ""),
    ("e34_num_div1_calc", "e56_data_mean_calc", "used_in", "medium", "printed p. 17, 31", "평균 구하기에 나눗셈이 쓰인다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e56_pat_rate", "e56_data_ratio_graph_draw", "used_in", "high", "printed p. 32 적용 시 고려 사항", "전체에 대한 각 부분의 비율 비교로 띠·원그래프의 필요성을 인식하게 한다", ""),
    ("e56_data_band_graph", "e56_data_ratio_graph_draw", "used_in", "high", "printed p. 31; [6수04-02]", "띠그래프로 나타내고 해석한다", ""),
    ("e56_data_pie_graph", "e56_data_ratio_graph_draw", "used_in", "high", "printed p. 31; [6수04-02]", "원그래프로 나타내고 해석한다", ""),
    ("e34_data_collect", "e56_data_inquiry", "used_in", "high", "printed p. 31; [6수04-03]", "탐구 문제에 맞는 자료를 수집, 정리한다", ""),
    ("e34_data_choose_graph", "e56_data_inquiry", "used_in", "high", "printed p. 31 성취기준 해설", "막대·꺾은선·띠·원그래프 중 적절한 그래프를 선택하게 한다", ""),
    ("e34_data_inquiry", "e56_data_inquiry", "prerequisite_for", "medium", "printed p. 23, 31", "통계적 탐구 과정 경험에서 탐구 문제 설정까지 포함하는 과정으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e56_data_possibility", "e56_data_possibility_words", "used_in", "high", "printed p. 31; [6수04-04]", "가능성을 말로 표현하고 비교한다", ""),
    ("e56_data_possibility_words", "e56_data_possibility_number", "prerequisite_for", "medium", "printed p. 31; [6수04-04]~[6수04-05]", "말 표현에서 수 표현으로 이어지는 성취기준 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e56_data_possibility_number", "e56_data_possibility_judge", "prerequisite_for", "medium", "printed p. 31; [6수04-05]~[6수04-06]", "가능성의 수 표현에서 자료 기반 판단으로 이어지는 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e56_data_inquiry", "e56_data_distortion", "related_to", "high", "printed p. 32 적용 시 고려 사항", "그래프 표현의 왜곡 여부를 비판적으로 판단하게 한다", ""),
]
