from __future__ import annotations

from elementary_common import concept, ref

# 초1-2 변화와 관계, 도형과 측정, 자료와 가능성 미시 concept.
# 근거: 별책8 인쇄 p.13~16 (PDF p.19~22)의 성취기준·해설·적용 시 고려 사항·용어와 기호.

GRADE = "초1-2"


def pat(cid, label, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "변화와 관계", "규칙 찾기", ctype, sdef, refs, **kw)


def geo(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "도형과 측정", unit, ctype, sdef, refs, **kw)


def dat(cid, label, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "자료와 가능성", "자료의 정리", ctype, sdef, refs, **kw)


CONCEPTS = [
    # ---------- 변화와 관계: 규칙 찾기 ----------
    pat("e12_pat_rule", "규칙", "core_concept",
        "물체, 무늬, 수 등의 배열에서 찾을 수 있는 일정한 질서.",
        [ref("printed p. 13; [2수02-01]", "achievement_standard", "배열에서 규칙을 찾아 여러 가지 방법으로 표현한다는 진술")]),
    pat("e12_pat_array", "물체·무늬·수의 배열", "representation",
        "규칙을 찾는 대상이 되는 물체, 무늬, 수 등의 배열.",
        [ref("printed p. 13; [2수02-01]", "achievement_standard", "물체, 무늬, 수 등의 배열이라는 진술")]),
    pat("e12_pat_find", "배열에서 규칙 찾기", "procedure",
        "배열을 관찰하여 규칙을 찾는 활동.",
        [ref("printed p. 13; [2수02-01]", "achievement_standard", "배열에서 규칙을 찾는다는 진술")]),
    pat("e12_pat_express", "규칙을 여러 가지 방법으로 표현하기", "procedure",
        "찾은 규칙을 말, 수, 그림, 기호, 구체물, 행동 등 다양한 방법으로 표현하는 활동.",
        [ref("printed p. 13; [2수02-01]", "achievement_standard", "규칙을 여러 가지 방법으로 표현한다는 진술"),
         ref("printed p. 13 성취기준 해설", "achievement_standard_note", "말, 수, 그림, 기호, 구체물, 행동 등의 다양한 방법으로 표현하게 한다")]),
    pat("e12_pat_repeat_grow", "반복되거나 증가하는 규칙", "sub_concept",
        "일정하게 반복되거나 증가하는 배열의 규칙.",
        [ref("printed p. 13 성취기준 해설", "achievement_standard_note", "일정하게 반복되거나 증가하는 규칙을 찾게 한다")]),
    pat("e12_pat_predict", "다음에 올 것과 빠진 것 추측하기", "procedure",
        "배열에서 다음에 올 것이나 중간에 빠진 것을 추측하는 활동.",
        [ref("printed p. 13 성취기준 해설", "achievement_standard_note", "다음에 올 것이나 중간에 빠진 것을 추측하게 한다")]),
    pat("e12_pat_make", "자신이 정한 규칙에 따라 배열하기", "procedure",
        "스스로 정한 규칙에 따라 물체, 무늬, 수 등을 배열하는 활동.",
        [ref("printed p. 13; [2수02-02]", "achievement_standard", "자신이 정한 규칙에 따라 배열할 수 있다는 진술")]),
    pat("e12_pat_attribute", "크기·색깔·위치·순서의 단순한 규칙", "sub_concept",
        "배열에서 다루는 크기, 색깔, 위치, 순서에 대한 단순한 규칙.",
        [ref("printed p. 13 적용 시 고려 사항", "teaching_note", "크기, 색깔, 위치, 순서 등에 대한 단순한 규칙을 다룬다")],
        notes="지나치게 복잡한 배열에 대한 평가는 지양한다(printed p. 13)."),
    pat("e12_pat_number_table", "수 배열표", "representation",
        "수를 배열하여 규칙을 찾는 데 활용하는 표.",
        [ref("printed p. 13 적용 시 고려 사항", "teaching_note", "수 배열표를 활용하여 수의 다양한 규칙을 찾게 한다")]),
    pat("e12_pat_addition_table", "덧셈표", "representation",
        "덧셈 결과를 배열하여 규칙을 찾는 데 활용하는 표.",
        [ref("printed p. 13 적용 시 고려 사항", "teaching_note", "덧셈표를 활용하여 수의 다양한 규칙을 찾게 한다")]),
    pat("e12_pat_tables_find", "수 배열표·덧셈표·곱셈표에서 규칙 찾기", "procedure",
        "수 배열표, 덧셈표, 곱셈표에서 수의 다양한 규칙을 찾는 활동.",
        [ref("printed p. 13 적용 시 고려 사항", "teaching_note", "수의 배열뿐만 아니라 수 배열표, 덧셈표, 곱셈표를 활용하여 규칙을 찾게 한다")]),
    pat("e12_pat_talk", "다른 사람의 배열에서 규칙 찾고 말하기", "procedure",
        "다른 사람의 배열에서 규칙을 찾아보거나 규칙에 대해 서로 말하는 활동.",
        [ref("printed p. 13 적용 시 고려 사항", "teaching_note", "다른 사람의 배열에서 규칙을 찾아보거나 규칙에 대해 서로 말하게 한다")]),
    # ---------- 도형과 측정: 입체도형의 모양 ----------
    geo("e12_geo_cuboid_shape", "직육면체 모양", "입체도형의 모양", "sub_concept",
        "생활 주변 물건에서 찾는 직육면체 모양.",
        [ref("printed p. 13; [2수03-01]", "achievement_standard", "직육면체, 원기둥, 구의 모양을 찾는다는 진술")]),
    geo("e12_geo_cylinder_shape", "원기둥 모양", "입체도형의 모양", "sub_concept",
        "생활 주변 물건에서 찾는 원기둥 모양.",
        [ref("printed p. 13; [2수03-01]", "achievement_standard", "직육면체, 원기둥, 구의 모양을 찾는다는 진술")]),
    geo("e12_geo_sphere_shape", "구 모양", "입체도형의 모양", "sub_concept",
        "생활 주변 물건에서 찾는 구 모양.",
        [ref("printed p. 13; [2수03-01]", "achievement_standard", "직육면체, 원기둥, 구의 모양을 찾는다는 진술")]),
    geo("e12_geo_find_solid", "생활 주변에서 입체 모양 찾기", "입체도형의 모양", "procedure",
        "교실 및 생활 주변의 여러 가지 물건을 관찰하여 입체도형 모양을 찾는 활동.",
        [ref("printed p. 13; [2수03-01]", "achievement_standard", "물건을 관찰하여 모양을 찾는다는 진술")]),
    geo("e12_geo_make_solid", "입체 모양으로 여러 가지 모양 만들기", "입체도형의 모양", "procedure",
        "찾은 입체 모양을 이용하여 여러 가지 모양을 만드는 활동.",
        [ref("printed p. 13; [2수03-01]", "achievement_standard", "이를 이용하여 여러 가지 모양을 만들 수 있다는 진술")],
        notes="모양 만들기 주제는 동물, 탈 것, 건물 등 친근한 소재로 제시한다(printed p. 15)."),
    geo("e12_geo_blocks", "쌓기나무로 모양 만들기", "입체도형의 모양", "procedure",
        "쌓기나무를 이용하여 여러 가지 입체도형의 모양을 만드는 활동.",
        [ref("printed p. 13; [2수03-02]", "achievement_standard", "쌓기나무를 이용하여 모양을 만든다는 진술")]),
    geo("e12_geo_position_words", "위치와 방향으로 모양 말하기", "입체도형의 모양", "procedure",
        "만든 모양에 대해 위치나 방향을 이용하여 말하는 활동.",
        [ref("printed p. 13; [2수03-02]", "achievement_standard", "위치나 방향을 이용하여 말할 수 있다는 진술"),
         ref("printed p. 14 성취기준 해설", "achievement_standard_note", "'~의 앞', '~의 오른쪽', '~의 위', '2층' 등을 사용하여 말하게 한다")]),
    geo("e12_geo_tangram", "칠교판", "입체도형의 모양", "representation",
        "모양 만들기에 이용하는 구체물.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "쌓기나무, 칠교판 등의 구체물을 이용한 모양 만들기")]),
    geo("e12_geo_spatial_sense", "도형에 대한 공간 감각", "입체도형의 모양", "sub_concept",
        "구체물을 이용한 모양 만들기를 통해 기르는 공간 감각.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "구체물을 이용한 모양 만들기를 통하여 공간 감각을 기르게 한다")]),
    # ---------- 도형과 측정: 평면도형과 그 구성 요소 ----------
    geo("e12_geo_triangle", "삼각형", "평면도형과 그 구성 요소", "core_concept",
        "직관적으로 이해하고 그릴 수 있는 평면도형.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 삼각형"),
         ref("printed p. 13; [2수03-03]", "achievement_standard", "삼각형, 사각형, 원의 모양을 찾는다는 진술")]),
    geo("e12_geo_quadrilateral", "사각형", "평면도형과 그 구성 요소", "core_concept",
        "직관적으로 이해하고 그릴 수 있는 평면도형.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 사각형"),
         ref("printed p. 13; [2수03-03]", "achievement_standard", "삼각형, 사각형, 원의 모양을 찾는다는 진술")]),
    geo("e12_geo_circle", "원", "평면도형과 그 구성 요소", "core_concept",
        "직관적으로 이해하고 그릴 수 있는 평면도형.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 원"),
         ref("printed p. 13; [2수03-03]", "achievement_standard", "삼각형, 사각형, 원의 모양을 찾는다는 진술")]),
    geo("e12_geo_vertex", "꼭짓점", "평면도형과 그 구성 요소", "term",
        "평면도형의 구성 요소를 가리키는 공식 용어.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 꼭짓점")]),
    geo("e12_geo_side", "변", "평면도형과 그 구성 요소", "term",
        "평면도형의 구성 요소를 가리키는 공식 용어.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 변")]),
    geo("e12_geo_find_plane", "생활 주변에서 평면 모양 찾기", "평면도형과 그 구성 요소", "procedure",
        "여러 가지 물건을 관찰하여 삼각형, 사각형, 원의 모양을 찾는 활동.",
        [ref("printed p. 13; [2수03-03]", "achievement_standard", "물건을 관찰하여 삼각형, 사각형, 원의 모양을 찾는다는 진술")]),
    geo("e12_geo_make_plane", "평면 모양으로 여러 가지 모양 만들기", "평면도형과 그 구성 요소", "procedure",
        "찾은 평면 모양을 이용하여 여러 가지 모양을 만드는 활동.",
        [ref("printed p. 13; [2수03-03]", "achievement_standard", "이를 이용하여 여러 가지 모양을 만들 수 있다는 진술")]),
    geo("e12_geo_intuitive", "삼각형·사각형·원 직관적으로 이해하기", "평면도형과 그 구성 요소", "procedure",
        "삼각형, 사각형, 원을 직관적으로 이해하는 활동.",
        [ref("printed p. 13; [2수03-04]", "achievement_standard", "삼각형, 사각형, 원을 직관적으로 이해한다는 진술")]),
    geo("e12_geo_example_sort", "예인 것과 예가 아닌 것 분류하기", "평면도형과 그 구성 요소", "procedure",
        "도형의 예인 것과 예가 아닌 것을 분류하는 활동.",
        [ref("printed p. 14 성취기준 해설", "achievement_standard_note", "예인 것과 예가 아닌 것을 분류하는 활동으로 직관적으로 이해하게 한다")]),
    geo("e12_geo_draw", "모양 그리기(본뜨기·도형판)", "평면도형과 그 구성 요소", "procedure",
        "본뜨기, 도형판을 이용한 활동 등으로 삼각형, 사각형, 원의 모양을 그리는 활동.",
        [ref("printed p. 13; [2수03-04]", "achievement_standard", "그 모양을 그릴 수 있다는 진술"),
         ref("printed p. 14 성취기준 해설", "achievement_standard_note", "본뜨기, 도형판을 이용한 활동 등을 통해 모양을 그리게 할 수 있다")]),
    geo("e12_geo_common", "삼각형과 사각형의 공통점 찾기", "평면도형과 그 구성 요소", "procedure",
        "삼각형, 사각형에서 각각의 공통점을 찾아 말하는 활동.",
        [ref("printed p. 14; [2수03-05]", "achievement_standard", "삼각형, 사각형에서 각각의 공통점을 찾아 말할 수 있다는 진술")]),
    # ---------- 도형과 측정: 양의 비교 ----------
    geo("e12_meas_compare_length", "길이 비교하기(길다·짧다)", "양의 비교", "procedure",
        "구체물의 길이를 비교하여 길다, 짧다로 구별하여 말하는 활동.",
        [ref("printed p. 14; [2수03-06]", "achievement_standard", "구체물의 길이를 비교하여 길다, 짧다를 구별한다는 진술")]),
    geo("e12_meas_compare_capacity", "들이 비교하기(많다·적다)", "양의 비교", "procedure",
        "구체물의 들이를 비교하여 많다, 적다로 구별하여 말하는 활동.",
        [ref("printed p. 14; [2수03-06]", "achievement_standard", "구체물의 들이를 비교하여 많다, 적다를 구별한다는 진술")]),
    geo("e12_meas_compare_weight", "무게 비교하기(무겁다·가볍다)", "양의 비교", "procedure",
        "구체물의 무게를 비교하여 무겁다, 가볍다로 구별하여 말하는 활동.",
        [ref("printed p. 14; [2수03-06]", "achievement_standard", "구체물의 무게를 비교하여 무겁다, 가볍다를 구별한다는 진술")]),
    geo("e12_meas_compare_area", "넓이 비교하기(넓다·좁다)", "양의 비교", "procedure",
        "구체물의 넓이를 비교하여 넓다, 좁다로 구별하여 말하는 활동.",
        [ref("printed p. 14; [2수03-06]", "achievement_standard", "구체물의 넓이를 비교하여 넓다, 좁다를 구별한다는 진술")]),
    geo("e12_meas_compare_methods", "직관적·직접·간접 비교", "양의 비교", "sub_concept",
        "양의 비교에서 상황에 따라 알맞게 다루는 비교 방법.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "직관적인 비교, 직접 비교, 간접 비교 등을 상황에 따라 알맞게 다룬다")]),
    # ---------- 도형과 측정: 시각과 시간 ----------
    geo("e12_meas_hour_term", "시", "시각과 시간", "term",
        "시각을 나타내는 공식 용어.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 시")]),
    geo("e12_meas_minute_term", "분", "시각과 시간", "term",
        "시각을 나타내는 공식 용어.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 분")]),
    geo("e12_meas_read_time", "시계 보고 몇 시 몇 분 읽기", "시각과 시간", "procedure",
        "시계를 보고 시각을 '몇 시 몇 분'까지 읽는 활동.",
        [ref("printed p. 14; [2수03-07]", "achievement_standard", "시계를 보고 시각을 몇 시 몇 분까지 읽을 수 있다는 진술")]),
    geo("e12_meas_time_before", "몇 시 몇 분 전으로 읽기", "시각과 시간", "procedure",
        "'몇 시 몇 분 전' 등의 방식으로 시각을 읽는 활동.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "'몇 시', '몇 시 30분', '몇 시 몇 분', '몇 시 몇 분 전' 등의 시각을 읽게 한다")],
        notes="5분 전, 10분 전과 같이 간단한 경우만 다루고 13분 전 같은 복잡한 경우는 다루지 않는다(printed p. 15)."),
    geo("e12_meas_model_clock", "모형 시계", "시각과 시간", "representation",
        "시각 읽기에 조작 활동으로 이용하는 도구.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "학생들이 모형 시계를 조작하여 시각을 읽게 한다")]),
    geo("e12_meas_hour_minute_rel", "1시간과 1분의 관계", "시각과 시간", "property",
        "1시간과 1분 사이의 관계.",
        [ref("printed p. 14; [2수03-08]", "achievement_standard", "1시간과 1분의 관계를 이해한다는 진술")]),
    geo("e12_meas_express_time", "시간을 '시간'과 '분'으로 표현하기", "시각과 시간", "procedure",
        "시간을 '시간', '분'으로 표현하는 활동.",
        [ref("printed p. 14; [2수03-08]", "achievement_standard", "시간을 '시간', '분'으로 표현할 수 있다는 진술")]),
    geo("e12_meas_time_units_rel", "1분·1시간·1일·1주일·1개월·1년 사이의 관계", "시각과 시간", "property",
        "실생활 문제 상황과 연결하여 이해하는 시간 단위 사이의 관계.",
        [ref("printed p. 14; [2수03-09]", "achievement_standard", "1분, 1시간, 1일, 1주일, 1개월, 1년 사이의 관계를 이해한다는 진술")],
        notes="단위 사이의 관계 이해에 중점을 두고 지나친 단위 환산은 다루지 않는다(printed p. 15)."),
    geo("e12_meas_calendar", "달력", "시각과 시간", "representation",
        "1일, 1주일, 1개월, 1년 사이의 관계를 이해하는 데 이용하는 표현.",
        [ref("printed p. 15 적용 시 고려 사항", "teaching_note", "실생활 상황에서 달력을 이용하여 그 관계를 이해하게 한다")]),
    # ---------- 도형과 측정: 길이 ----------
    geo("e12_meas_cm", "길이 단위 1cm", "길이", "term",
        "길이의 표준 단위 1cm.",
        [ref("printed p. 14; [2수03-10]", "achievement_standard", "길이 단위 1cm와 1m를 안다는 진술"),
         ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 기호 목록의 cm")]),
    geo("e12_meas_m", "길이 단위 1m", "길이", "term",
        "길이의 표준 단위 1m.",
        [ref("printed p. 14; [2수03-10]", "achievement_standard", "길이 단위 1cm와 1m를 안다는 진술"),
         ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 기호 목록의 m")]),
    geo("e12_meas_informal_units", "임의 단위로 길이 재기", "길이", "procedure",
        "표준 단위 도입 전에 여러 가지 임의 단위로 구체물의 길이를 재어 보는 활동.",
        [ref("printed p. 14 성취기준 해설", "achievement_standard_note", "여러 가지 임의 단위를 사용하여 길이를 재어보는 활동을 통해 표준 단위의 필요성을 알게 한다")]),
    geo("e12_meas_standard_need", "표준 단위의 필요성", "길이", "property",
        "임의 단위 측정 경험을 통해 알게 되는 표준 단위의 필요성.",
        [ref("printed p. 14 성취기준 해설", "achievement_standard_note", "표준 단위의 필요성을 알게 한다")]),
    geo("e12_meas_measure_length", "자로 주변 사물의 길이 측정하기", "길이", "procedure",
        "1cm와 1m를 이용하여 주변 사물의 길이를 측정하는 활동.",
        [ref("printed p. 14; [2수03-10]", "achievement_standard", "이를 이용하여 주변 사물의 길이를 측정할 수 있다는 진술")]),
    geo("e12_meas_m_cm_rel", "1m와 1cm의 관계", "길이", "property",
        "1m와 1cm 사이의 관계.",
        [ref("printed p. 14; [2수03-11]", "achievement_standard", "1m와 1cm의 관계를 이해한다는 진술")]),
    geo("e12_meas_express_length", "길이를 '몇 m 몇 cm'와 '몇 cm'로 표현하기", "길이", "procedure",
        "길이를 '몇 m 몇 cm'와 '몇 cm'로 표현하는 활동.",
        [ref("printed p. 14; [2수03-11]", "achievement_standard", "길이를 '몇 m 몇 cm'와 '몇 cm'로 표현할 수 있다는 진술")]),
    geo("e12_meas_estimate", "길이 어림하기", "길이", "procedure",
        "여러 가지 물건의 길이를 어림하는 활동.",
        [ref("printed p. 14; [2수03-12]", "achievement_standard", "여러 가지 물건의 길이를 어림한다는 진술"),
         ref("printed p. 14 성취기준 해설", "achievement_standard_note", "어림해 보고 자로 측정하여 확인하는 활동과 주어진 길이의 선분을 그려 보는 활동")]),
    geo("e12_meas_length_sense", "길이에 대한 양감", "길이", "sub_concept",
        "어림과 측정 활동을 통해 기르는 길이에 대한 양감.",
        [ref("printed p. 14; [2수03-12]", "achievement_standard", "길이에 대한 양감을 기른다는 진술")]),
    geo("e12_meas_approx", "약(어림 표현)", "길이", "term",
        "자의 눈금과 일치하지 않는 측정값을 나타내는 표현.",
        [ref("printed p. 14 용어와 기호", "term_list", "도형과 측정 영역 용어 목록의 약"),
         ref("printed p. 15 적용 시 고려 사항", "teaching_note", "눈금과 일치하지 않는 길이의 측정값을 '약'으로 표현할 수 있음을 알게 한다")]),
    geo("e12_meas_length_addsub", "길이의 덧셈과 뺄셈", "길이", "procedure",
        "실생활 문제 상황과 연결하여 길이의 덧셈과 뺄셈을 하는 활동.",
        [ref("printed p. 14; [2수03-13]", "achievement_standard", "실생활 문제 상황과 연결하여 길이의 덧셈과 뺄셈을 할 수 있다는 진술")]),
    # ---------- 자료와 가능성: 자료의 정리 ----------
    dat("e12_data_classify", "기준에 따라 분류하기", "procedure",
        "여러 가지 사물을 정해진 기준 또는 자신이 정한 기준으로 분류하는 활동.",
        [ref("printed p. 15; [2수04-01]", "achievement_standard", "정해진 기준 또는 자신이 정한 기준으로 분류한다는 진술")]),
    dat("e12_data_criteria", "분류 기준 정하기", "procedure",
        "분류를 위해 기준을 정하는 활동.",
        [ref("printed p. 15; [2수04-01]", "achievement_standard", "자신이 정한 기준으로 분류한다는 진술")],
        notes="분명하지 않은 기준으로는 분류하기가 어렵다는 점을 인식하게 한다(printed p. 16)."),
    dat("e12_data_count", "분류한 결과의 개수 세기", "procedure",
        "분류한 사물의 개수를 세어 보는 활동.",
        [ref("printed p. 15; [2수04-01]", "achievement_standard", "분류하여 개수를 세어 본다는 진술")]),
    dat("e12_data_state", "기준에 따른 분류 결과 말하기", "procedure",
        "기준에 따른 분류 결과를 말하는 활동.",
        [ref("printed p. 15; [2수04-01]", "achievement_standard", "기준에 따른 결과를 말할 수 있다는 진술")]),
    dat("e12_data_table", "표", "term",
        "자료를 분류하여 정리하는 공식 표현.",
        [ref("printed p. 16 용어와 기호", "term_list", "자료와 가능성 영역 용어 목록의 표")]),
    dat("e12_data_to_table", "자료를 분류하여 표로 나타내기", "procedure",
        "자료를 분류하여 표로 나타내는 활동.",
        [ref("printed p. 15; [2수04-02]", "achievement_standard", "자료를 분류하여 표로 나타낸다는 진술")]),
    dat("e12_data_table_benefit", "자료를 표로 나타내면 편리한 점", "property",
        "표로 자료의 크기를 수로 정리하면 나타내고 비교하기 편리함.",
        [ref("printed p. 15; [2수04-02]", "achievement_standard", "자료를 표로 나타내면 편리한 점을 말할 수 있다는 진술"),
         ref("printed p. 16 성취기준 해설", "achievement_standard_note", "자료의 크기를 수로 정리하면 나타내고 비교하는 데 편리하다는 점으로 수학의 유용성을 인식하게 한다")]),
    dat("e12_data_graph", "그래프", "term",
        "자료를 분류하여 시각적으로 나타내는 공식 표현.",
        [ref("printed p. 16 용어와 기호", "term_list", "자료와 가능성 영역 용어 목록의 그래프")]),
    dat("e12_data_to_graph", "○·×·/를 이용한 그래프로 나타내기", "procedure",
        "자료를 분류하여 ○, ×, / 등을 이용한 그래프로 나타내는 활동.",
        [ref("printed p. 15; [2수04-03]", "achievement_standard", "○, ×, / 등을 이용한 그래프로 나타낸다는 진술")]),
    dat("e12_data_graph_benefit", "자료를 그래프로 나타내면 편리한 점", "property",
        "그래프로 자료의 크기를 시각적으로 나타내면 한눈에 비교하기 편리함.",
        [ref("printed p. 15; [2수04-03]", "achievement_standard", "자료를 그래프로 나타내면 편리한 점을 말할 수 있다는 진술"),
         ref("printed p. 16 성취기준 해설", "achievement_standard_note", "자료의 크기를 시각적으로 나타내면 한눈에 비교하는 데 편리하다는 점으로 수학의 유용성을 인식하게 한다")]),
    dat("e12_data_no_miss", "자료를 중복·누락 없이 세기", "procedure",
        "표나 그래프를 만들 때 자료가 중복되거나 빠지지 않도록 세어 보는 방법.",
        [ref("printed p. 16 적용 시 고려 사항", "teaching_note", "자료가 중복되거나 빠지지 않도록 세어 보는 방법을 함께 지도한다")]),
]

# (source_id, target_id, relationship_type, confidence, locator, summary, notes)
EDGE_DEFS = [
    # 변화와 관계
    ("e12_pat_rule", "e12_pat_repeat_grow", "contains", "high", "printed p. 13 성취기준 해설", "반복되거나 증가하는 규칙은 배열에서 찾는 규칙의 유형이다", ""),
    ("e12_pat_rule", "e12_pat_attribute", "contains", "high", "printed p. 13 적용 시 고려 사항", "크기·색깔·위치·순서의 단순한 규칙은 다루는 규칙의 범위다", ""),
    ("e12_pat_find", "e12_pat_tables_find", "contains", "high", "printed p. 13 적용 시 고려 사항", "수 배열표·덧셈표·곱셈표에서 규칙 찾기는 규칙 찾기의 확장 활동이다", ""),
    ("e12_pat_find", "e12_pat_talk", "contains", "high", "printed p. 13 적용 시 고려 사항", "다른 사람의 배열에서 규칙 찾기는 규칙 찾기의 소통 활동이다", ""),
    ("e12_pat_array", "e12_pat_find", "used_in", "high", "printed p. 13; [2수02-01]", "물체, 무늬, 수 등의 배열에서 규칙을 찾는다", ""),
    ("e12_pat_find", "e12_pat_express", "prerequisite_for", "high", "printed p. 13; [2수02-01]", "규칙을 찾아 여러 가지 방법으로 표현한다는 진술 구조", ""),
    ("e12_pat_find", "e12_pat_predict", "prerequisite_for", "high", "printed p. 13 성취기준 해설", "규칙을 찾고 다음에 올 것이나 빠진 것을 추측하게 한다는 해설 구조", ""),
    ("e12_pat_rule", "e12_pat_make", "used_in", "high", "printed p. 13; [2수02-02]", "자신이 정한 규칙에 따라 배열한다", ""),
    ("e12_pat_number_table", "e12_pat_tables_find", "used_in", "high", "printed p. 13 적용 시 고려 사항", "수 배열표를 활용하여 규칙을 찾게 한다", ""),
    ("e12_pat_addition_table", "e12_pat_tables_find", "used_in", "high", "printed p. 13 적용 시 고려 사항", "덧셈표를 활용하여 규칙을 찾게 한다", ""),
    ("e12_mul_table", "e12_pat_tables_find", "used_in", "high", "printed p. 13 적용 시 고려 사항", "곱셈표를 활용하여 수의 다양한 규칙을 찾게 한다", ""),
    # 도형과 측정: 입체
    ("e12_geo_find_solid", "e12_geo_cuboid_shape", "used_in", "high", "printed p. 13; [2수03-01]", "물건을 관찰하여 직육면체 모양을 찾는다", ""),
    ("e12_geo_find_solid", "e12_geo_cylinder_shape", "used_in", "high", "printed p. 13; [2수03-01]", "물건을 관찰하여 원기둥 모양을 찾는다", ""),
    ("e12_geo_find_solid", "e12_geo_sphere_shape", "used_in", "high", "printed p. 13; [2수03-01]", "물건을 관찰하여 구 모양을 찾는다", ""),
    ("e12_geo_find_solid", "e12_geo_make_solid", "prerequisite_for", "high", "printed p. 13; [2수03-01]", "모양을 찾고 이를 이용하여 여러 가지 모양을 만든다는 진술 구조", ""),
    ("e12_geo_blocks", "e12_geo_position_words", "prerequisite_for", "high", "printed p. 13; [2수03-02]", "쌓기나무로 모양을 만들고 그 모양에 대해 말한다는 진술 구조", ""),
    ("e12_geo_blocks", "e12_geo_spatial_sense", "used_in", "high", "printed p. 15 적용 시 고려 사항", "쌓기나무 등을 이용한 모양 만들기를 통하여 공간 감각을 기르게 한다", ""),
    ("e12_geo_tangram", "e12_geo_spatial_sense", "used_in", "high", "printed p. 15 적용 시 고려 사항", "칠교판 등을 이용한 모양 만들기를 통하여 공간 감각을 기르게 한다", ""),
    # 도형과 측정: 평면
    ("e12_geo_find_plane", "e12_geo_triangle", "used_in", "high", "printed p. 13; [2수03-03]", "물건을 관찰하여 삼각형 모양을 찾는다", ""),
    ("e12_geo_find_plane", "e12_geo_quadrilateral", "used_in", "high", "printed p. 13; [2수03-03]", "물건을 관찰하여 사각형 모양을 찾는다", ""),
    ("e12_geo_find_plane", "e12_geo_circle", "used_in", "high", "printed p. 13; [2수03-03]", "물건을 관찰하여 원 모양을 찾는다", ""),
    ("e12_geo_find_plane", "e12_geo_make_plane", "prerequisite_for", "high", "printed p. 13; [2수03-03]", "모양을 찾고 이를 이용하여 여러 가지 모양을 만든다는 진술 구조", ""),
    ("e12_geo_example_sort", "e12_geo_intuitive", "used_in", "high", "printed p. 14 성취기준 해설", "예인 것과 예가 아닌 것을 분류하는 활동으로 직관적으로 이해하게 한다", ""),
    ("e12_geo_intuitive", "e12_geo_draw", "prerequisite_for", "high", "printed p. 13; [2수03-04]", "직관적으로 이해하고 그 모양을 그릴 수 있다는 진술 구조", ""),
    ("e12_geo_triangle", "e12_geo_common", "used_in", "high", "printed p. 14; [2수03-05]", "삼각형에서 공통점을 찾아 말한다", ""),
    ("e12_geo_quadrilateral", "e12_geo_common", "used_in", "high", "printed p. 14; [2수03-05]", "사각형에서 공통점을 찾아 말한다", ""),
    ("e12_geo_triangle", "e12_geo_intuitive", "related_to", "high", "printed p. 13; [2수03-04]", "직관적 이해의 대상 도형", ""),
    ("e12_geo_quadrilateral", "e12_geo_intuitive", "related_to", "high", "printed p. 13; [2수03-04]", "직관적 이해의 대상 도형", ""),
    ("e12_geo_circle", "e12_geo_intuitive", "related_to", "high", "printed p. 13; [2수03-04]", "직관적 이해의 대상 도형", ""),
    # 도형과 측정: 양의 비교
    ("e12_meas_compare_methods", "e12_meas_compare_length", "used_in", "high", "printed p. 15 적용 시 고려 사항", "직관적·직접·간접 비교를 상황에 따라 알맞게 다룬다", ""),
    ("e12_meas_compare_methods", "e12_meas_compare_capacity", "used_in", "high", "printed p. 15 적용 시 고려 사항", "직관적·직접·간접 비교를 상황에 따라 알맞게 다룬다", ""),
    ("e12_meas_compare_methods", "e12_meas_compare_weight", "used_in", "high", "printed p. 15 적용 시 고려 사항", "직관적·직접·간접 비교를 상황에 따라 알맞게 다룬다", ""),
    ("e12_meas_compare_methods", "e12_meas_compare_area", "used_in", "high", "printed p. 15 적용 시 고려 사항", "직관적·직접·간접 비교를 상황에 따라 알맞게 다룬다", ""),
    # 도형과 측정: 시각과 시간
    ("e12_meas_hour_term", "e12_meas_read_time", "used_in", "high", "printed p. 14; [2수03-07]", "시각을 '몇 시 몇 분'까지 읽는다", ""),
    ("e12_meas_minute_term", "e12_meas_read_time", "used_in", "high", "printed p. 14; [2수03-07]", "시각을 '몇 시 몇 분'까지 읽는다", ""),
    ("e12_meas_read_time", "e12_meas_time_before", "prerequisite_for", "medium", "printed p. 15 적용 시 고려 사항", "'몇 시 몇 분' 읽기에 이어 '몇 시 몇 분 전' 읽기를 다룬다", "고려 사항의 시각 읽기 나열 순서에서 추론한 관계다."),
    ("e12_meas_model_clock", "e12_meas_read_time", "used_in", "high", "printed p. 15 적용 시 고려 사항", "모형 시계를 조작하여 시각을 읽게 한다", ""),
    ("e12_meas_hour_minute_rel", "e12_meas_express_time", "prerequisite_for", "high", "printed p. 14; [2수03-08]", "1시간과 1분의 관계를 이해하고 시간을 표현한다는 진술 구조", ""),
    ("e12_meas_calendar", "e12_meas_time_units_rel", "used_in", "high", "printed p. 15 적용 시 고려 사항", "달력을 이용하여 시간 단위 사이의 관계를 이해하게 한다", ""),
    ("e12_meas_hour_minute_rel", "e12_meas_time_units_rel", "related_to", "high", "printed p. 14; [2수03-08], [2수03-09]", "시간 단위 사이의 관계로 함께 다루는 성취기준", ""),
    # 도형과 측정: 길이
    ("e12_meas_informal_units", "e12_meas_standard_need", "prerequisite_for", "high", "printed p. 14 성취기준 해설", "임의 단위 측정 활동을 통해 표준 단위의 필요성을 알게 한다", ""),
    ("e12_meas_standard_need", "e12_meas_cm", "prerequisite_for", "high", "printed p. 14 성취기준 해설", "표준 단위의 필요성을 안 뒤 길이의 표준 단위를 도입한다", ""),
    ("e12_meas_standard_need", "e12_meas_m", "prerequisite_for", "high", "printed p. 14 성취기준 해설", "표준 단위의 필요성을 안 뒤 길이의 표준 단위를 도입한다", ""),
    ("e12_meas_cm", "e12_meas_measure_length", "used_in", "high", "printed p. 14; [2수03-10]", "1cm를 이용하여 주변 사물의 길이를 측정한다", ""),
    ("e12_meas_m", "e12_meas_measure_length", "used_in", "high", "printed p. 14; [2수03-10]", "1m를 이용하여 주변 사물의 길이를 측정한다", ""),
    ("e12_meas_m_cm_rel", "e12_meas_express_length", "prerequisite_for", "high", "printed p. 14; [2수03-11]", "1m와 1cm의 관계를 이해하고 길이를 표현한다는 진술 구조", ""),
    ("e12_meas_measure_length", "e12_meas_estimate", "related_to", "high", "printed p. 14 성취기준 해설", "어림해 보고 자로 측정하여 확인하는 활동이 함께 제시된다", ""),
    ("e12_meas_estimate", "e12_meas_length_sense", "used_in", "high", "printed p. 14; [2수03-12]", "어림 활동을 통해 길이에 대한 양감을 기른다", ""),
    ("e12_meas_approx", "e12_meas_measure_length", "used_in", "high", "printed p. 15 적용 시 고려 사항", "눈금과 일치하지 않는 측정값을 '약'으로 표현할 수 있음을 알게 한다", ""),
    ("e12_add", "e12_meas_length_addsub", "used_in", "high", "printed p. 14; [2수03-13]", "길이의 덧셈을 실생활 문제 상황과 연결하여 다룬다", ""),
    ("e12_sub", "e12_meas_length_addsub", "used_in", "high", "printed p. 14; [2수03-13]", "길이의 뺄셈을 실생활 문제 상황과 연결하여 다룬다", ""),
    ("e12_meas_cm", "e12_meas_length_addsub", "used_in", "medium", "printed p. 14; [2수03-13]", "길이의 덧셈과 뺄셈은 길이 단위 표현을 전제로 한다", "진술이 단위를 직접 언급하지 않으므로 medium을 유지한다."),
    # 자료와 가능성
    ("e12_data_criteria", "e12_data_classify", "prerequisite_for", "high", "printed p. 15; [2수04-01]", "기준을 정해 분류한다는 진술 구조", ""),
    ("e12_data_classify", "e12_data_count", "prerequisite_for", "high", "printed p. 15; [2수04-01]", "분류하여 개수를 세어 본다는 진술 구조", ""),
    ("e12_data_count", "e12_data_state", "prerequisite_for", "high", "printed p. 15; [2수04-01]", "개수를 세어 보고 결과를 말한다는 진술 구조", ""),
    ("e12_num_counting", "e12_data_count", "used_in", "high", "printed p. 15; [2수04-01]", "분류한 사물의 개수를 세는 활동에 수 세기를 사용한다", ""),
    ("e12_data_classify", "e12_data_to_table", "prerequisite_for", "high", "printed p. 15; [2수04-02]", "자료를 분류하여 표로 나타낸다는 진술 구조", ""),
    ("e12_data_classify", "e12_data_to_graph", "prerequisite_for", "high", "printed p. 15; [2수04-03]", "자료를 분류하여 그래프로 나타낸다는 진술 구조", ""),
    ("e12_data_table", "e12_data_to_table", "used_in", "high", "printed p. 15; [2수04-02]", "자료를 표로 나타낸다", ""),
    ("e12_data_graph", "e12_data_to_graph", "used_in", "high", "printed p. 15; [2수04-03]", "자료를 그래프로 나타낸다", ""),
    ("e12_data_to_table", "e12_data_table_benefit", "used_in", "high", "printed p. 15; [2수04-02]", "표로 나타내면 편리한 점을 말한다", ""),
    ("e12_data_to_graph", "e12_data_graph_benefit", "used_in", "high", "printed p. 15; [2수04-03]", "그래프로 나타내면 편리한 점을 말한다", ""),
    ("e12_data_no_miss", "e12_data_to_table", "used_in", "high", "printed p. 16 적용 시 고려 사항", "표를 만들 때 중복되거나 빠지지 않도록 세어 보는 방법을 지도한다", ""),
    ("e12_data_no_miss", "e12_data_to_graph", "used_in", "high", "printed p. 16 적용 시 고려 사항", "그래프를 만들 때 중복되거나 빠지지 않도록 세어 보는 방법을 지도한다", ""),
]
