from __future__ import annotations

from elementary_common import concept, ref

# 초3-4 전체 4개 영역 미시 concept.
# 근거: 별책8 인쇄 p.17~24 (PDF p.23~30)의 성취기준·해설·적용 시 고려 사항·용어와 기호.

GRADE = "초3-4"


def num(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "수와 연산", unit, ctype, sdef, refs, **kw)


def pat(cid, label, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "변화와 관계", "규칙을 수나 식으로 나타내기와 동치 관계", ctype, sdef, refs, **kw)


def geo(cid, label, unit, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "도형과 측정", unit, ctype, sdef, refs, **kw)


def dat(cid, label, ctype, sdef, refs, **kw):
    return concept(cid, label, GRADE, "자료와 가능성", "자료의 수집과 정리", ctype, sdef, refs, **kw)


def std(page, code, summary):
    return ref(f"printed p. {page}; [{code}]", "achievement_standard", summary)


def note(page, summary):
    return ref(f"printed p. {page} 성취기준 해설", "achievement_standard_note", summary)


def tnote(page, summary):
    return ref(f"printed p. {page} 적용 시 고려 사항", "teaching_note", summary)


def term(page, name):
    return ref(f"printed p. {page} 용어와 기호", "term_list", f"용어 목록의 {name}")


CONCEPTS = [
    # ---------- 수와 연산: 다섯 자리 이상의 수 ----------
    num("e34_num_big", "10000 이상의 큰 수", "다섯 자리 이상의 수", "core_concept",
        "큰 수의 필요성을 인식하며 이해하는 10000 이상의 수.",
        [std(17, "4수01-01", "10000 이상의 큰 수에 대한 자릿값과 위치적 기수법을 이해한다는 진술")]),
    num("e34_num_big_place", "큰 수의 자릿값과 위치적 기수법", "다섯 자리 이상의 수", "sub_concept",
        "다섯 자리 이상의 수에서의 자릿값과 위치적 기수법.",
        [std(17, "4수01-01", "자릿값과 위치적 기수법을 이해하고 수를 읽고 쓴다는 진술")]),
    num("e34_num_big_need", "큰 수의 필요성 인식과 양감", "다섯 자리 이상의 수", "procedure",
        "매체 자료 조사로 실생활에서 큰 수가 쓰이는 경우를 찾고 양감을 기르는 활동.",
        [tnote(18, "뉴스, 광고 등 매체를 활용한 조사로 큰 수의 필요성을 인식하고 양감을 기르게 한다")]),
    num("e34_num_big_compare", "다섯 자리 이상 수의 계열 이해와 크기 비교", "다섯 자리 이상의 수", "procedure",
        "다섯 자리 이상의 수의 범위에서 수의 계열을 이해하고 크기를 비교하며 방법을 설명하는 활동.",
        [std(17, "4수01-02", "수의 계열을 이해하고 크기를 비교하며 그 방법을 설명한다는 진술")]),
    # ---------- 수와 연산: 세 자리 수의 덧셈과 뺄셈 ----------
    num("e34_num_addsub3", "세 자리 수의 덧셈과 뺄셈", "세 자리 수의 덧셈과 뺄셈", "procedure",
        "세 자리 수의 덧셈과 뺄셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(17, "4수01-03", "계산 원리를 이해하고 그 계산을 할 수 있다는 진술"),
         note(18, "덧셈은 세 자리 수의 범위에서 다루되 합이 네 자리 수인 경우도 포함한다")]),
    # ---------- 수와 연산: 세 자리 수 범위의 곱셈 ----------
    num("e34_num_mul_multi", "곱하는 수가 한·두 자리 수인 곱셈", "세 자리 수 범위의 곱셈", "procedure",
        "곱하는 수가 한 자리 수 또는 두 자리 수인 곱셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(17, "4수01-04", "곱셈의 계산 원리를 이해하고 그 계산을 할 수 있다는 진술"),
         note(18, "(두 자리 수)×(한 자리 수), (세 자리 수)×(한 자리 수), (두 자리 수)×(두 자리 수), (세 자리 수)×(두 자리 수)를 다룬다")]),
    # ---------- 수와 연산: 세 자리 수 범위의 나눗셈 ----------
    num("e34_num_div", "나눗셈", "세 자리 수 범위의 나눗셈", "core_concept",
        "실생활 상황과 연결하여 의미를 아는 연산.",
        [term(18, "나눗셈"), std(17, "4수01-05", "나눗셈이 이루어지는 실생활 상황과 연결하여 나눗셈의 의미를 안다는 진술")]),
    num("e34_num_div_symbol", "나눗셈 기호 ÷", "세 자리 수 범위의 나눗셈", "term",
        "나눗셈을 나타내는 기호 ÷.",
        [term(18, "÷")]),
    num("e34_num_mul_div_rel", "곱셈과 나눗셈의 관계", "세 자리 수 범위의 나눗셈", "property",
        "곱셈과 나눗셈이 서로 연결되는 관계.",
        [std(17, "4수01-05", "곱셈과 나눗셈의 관계를 이해한다는 진술"),
         tnote(18, "한 가지 상황을 곱셈식과 나눗셈식으로 나타내는 활동으로 관계를 이해하게 한다")]),
    num("e34_num_quotient", "몫", "세 자리 수 범위의 나눗셈", "term",
        "나눗셈의 결과를 가리키는 공식 용어.",
        [term(18, "몫"), std(17, "4수01-06", "나눗셈에서 몫과 나머지의 의미를 안다는 진술")]),
    num("e34_num_remainder", "나머지", "세 자리 수 범위의 나눗셈", "term",
        "나눗셈에서 남는 수를 가리키는 공식 용어.",
        [term(18, "나머지"), std(17, "4수01-06", "나눗셈에서 몫과 나머지의 의미를 안다는 진술")]),
    num("e34_num_divisible", "나누어떨어진다", "세 자리 수 범위의 나눗셈", "term",
        "나머지가 없이 나누어지는 경우를 가리키는 공식 용어.",
        [term(18, "나누어떨어진다"),
         note(18, "(두 자리 수)÷(한 자리 수)는 나누어떨어지는 경우와 나누어떨어지지 않는 경우를 포함한다")]),
    num("e34_num_div1_calc", "나누는 수가 한 자리 수인 나눗셈", "세 자리 수 범위의 나눗셈", "procedure",
        "나누는 수가 한 자리 수인 나눗셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(17, "4수01-06", "계산 원리를 이해하고 그 계산을 할 수 있다는 진술")]),
    num("e34_num_div2_calc", "나누는 수가 두 자리 수인 나눗셈", "세 자리 수 범위의 나눗셈", "procedure",
        "나누는 수가 두 자리 수인 나눗셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(17, "4수01-07", "계산 원리를 이해하고 그 계산을 할 수 있다는 진술"),
         note(18, "(두 자리 수)÷(두 자리 수), (세 자리 수)÷(두 자리 수)를 다룬다")]),
    num("e34_num_div_check", "나눗셈 검산하기", "세 자리 수 범위의 나눗셈", "procedure",
        "나눗셈의 결과를 확인하는 활동.",
        [tnote(18, "검산에서는 검산의 목적과 필요성을 이해하는 데 초점을 둔다")]),
    # ---------- 수와 연산: 자연수의 어림셈 ----------
    num("e34_num_estimation", "자연수의 어림셈", "자연수의 어림셈", "procedure",
        "자연수의 사칙연산과 관련한 여러 가지 상황에서 어림셈을 하는 활동.",
        [std(17, "4수01-08", "여러 가지 상황에서 어림셈을 할 수 있다는 진술"),
         tnote(19, "계산 전 결과 어림하기, 어림한 값으로 계산 결과의 타당성 확인하기 등을 다룰 수 있다")]),
    # ---------- 수와 연산: 분수 ----------
    num("e34_num_fraction", "분수", "분수", "core_concept",
        "양의 등분할을 통하여 도입하는 수.",
        [term(18, "분수"), std(17, "4수01-09", "분수의 필요성을 인식하고 분수를 이해하고 읽고 쓸 수 있다는 진술")]),
    num("e34_num_partition", "양의 등분할", "분수", "sub_concept",
        "전체를 똑같이 나누어 부분과 전체를 파악하는 활동.",
        [std(17, "4수01-09", "양의 등분할을 통하여 분수의 필요성을 인식한다는 진술"),
         note(18, "양의 등분할로 분수를 도입할 때 부분과 전체를 파악하게 한다")]),
    num("e34_num_fraction_need", "분수의 필요성 인식하기", "분수", "procedure",
        "1보다 작은 양을 나타내는 경우를 통해 분수의 필요성과 표현의 편리함을 인식하는 활동.",
        [note(18, "1보다 작은 양을 나타내는 경우로 분수의 필요성이나 표현의 편리함을 인식하게 할 수 있다")]),
    num("e34_num_denominator", "분모", "분수", "term",
        "분수 표기에서 아래에 쓰는 수를 가리키는 공식 용어.",
        [term(18, "분모"), note(18, "'분모', '분자'를 사용한다")]),
    num("e34_num_numerator", "분자", "분수", "term",
        "분수 표기에서 위에 쓰는 수를 가리키는 공식 용어.",
        [term(18, "분자"), note(18, "'분모', '분자'를 사용한다")]),
    num("e34_num_unit_fraction", "단위분수", "분수", "term",
        "분자가 1인 분수를 가리키는 공식 용어.",
        [term(18, "단위분수"), std(17, "4수01-10", "단위분수, 진분수, 가분수, 대분수를 알고 관계를 이해한다는 진술")]),
    num("e34_num_proper", "진분수", "분수", "term",
        "분자가 분모보다 작은 분수를 가리키는 공식 용어.",
        [term(18, "진분수"), std(17, "4수01-10", "단위분수, 진분수, 가분수, 대분수를 알고 관계를 이해한다는 진술")]),
    num("e34_num_improper", "가분수", "분수", "term",
        "분자가 분모와 같거나 큰 분수를 가리키는 공식 용어.",
        [term(18, "가분수"), std(17, "4수01-10", "단위분수, 진분수, 가분수, 대분수를 알고 관계를 이해한다는 진술")]),
    num("e34_num_mixed", "대분수", "분수", "term",
        "자연수와 진분수로 나타낸 분수를 가리키는 공식 용어.",
        [term(18, "대분수"), std(17, "4수01-10", "단위분수, 진분수, 가분수, 대분수를 알고 관계를 이해한다는 진술")]),
    num("e34_num_fraction_types_rel", "분수 종류 사이의 관계", "분수", "property",
        "단위분수, 진분수, 가분수, 대분수 사이의 관계.",
        [std(17, "4수01-10", "그 관계를 이해한다는 진술")]),
    num("e34_num_fraction_compare", "분모가 같은 분수·단위분수의 크기 비교", "분수", "procedure",
        "분모가 같은 분수끼리, 단위분수끼리 크기를 비교하고 방법을 설명하는 활동.",
        [std(17, "4수01-11", "크기를 비교하고 그 방법을 설명할 수 있다는 진술")]),
    # ---------- 수와 연산: 소수 ----------
    num("e34_num_natural", "자연수", "소수", "term",
        "수 체계를 가리키는 공식 용어.",
        [term(18, "자연수")]),
    num("e34_num_decimal", "소수", "소수", "core_concept",
        "분모가 10인 진분수와 연결하여 도입하는 수.",
        [term(18, "소수"), std(17, "4수01-12", "분모가 10인 진분수와 연결하여 소수 한 자리 수를 이해한다는 진술")]),
    num("e34_num_decimal_point", "소수점(.)", "소수", "term",
        "소수 표기에 쓰는 기호.",
        [term(18, "소수점(.)")]),
    num("e34_num_decimal1", "소수 한 자리 수", "소수", "sub_concept",
        "분모가 10인 진분수와 연결하여 이해하는 소수.",
        [std(17, "4수01-12", "소수 한 자리 수를 이해하고 읽고 쓸 수 있다는 진술")]),
    num("e34_num_decimal23", "소수 두 자리 수와 세 자리 수", "소수", "sub_concept",
        "자릿값의 원리를 바탕으로 이해하는 소수.",
        [std(18, "4수01-13", "자릿값의 원리를 바탕으로 소수 두 자리 수와 세 자리 수를 이해한다는 진술")]),
    num("e34_num_decimal_compare", "소수의 크기 비교", "소수", "procedure",
        "소수의 크기를 비교하고 방법을 설명하는 활동.",
        [std(18, "4수01-14", "소수의 크기를 비교하고 그 방법을 설명할 수 있다는 진술")]),
    num("e34_num_decimal_need", "소수의 필요성 인식하기", "소수", "procedure",
        "실생활에서 소수를 활용한 사례를 통해 소수의 필요성을 인식하는 활동.",
        [tnote(19, "실생활에서 소수를 활용한 사례를 통해 소수의 필요성을 인식하게 한다")]),
    # ---------- 수와 연산: 분수·소수의 덧셈과 뺄셈 ----------
    num("e34_num_fraction_addsub", "분모가 같은 분수의 덧셈과 뺄셈", "분수의 덧셈과 뺄셈", "procedure",
        "분모가 같은 분수의 덧셈과 뺄셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(18, "4수01-15", "계산 원리를 이해하고 그 계산을 할 수 있다는 진술")]),
    num("e34_num_decimal_addsub", "소수의 덧셈과 뺄셈", "소수의 덧셈과 뺄셈", "procedure",
        "소수 두 자리 수의 범위에서 소수의 덧셈과 뺄셈의 계산 원리를 이해하고 계산하는 활동.",
        [std(18, "4수01-16", "소수 두 자리 수의 범위에서 계산 원리를 이해하고 계산한다는 진술"),
         tnote(19, "소수의 덧셈과 뺄셈은 계산 원리를 이해할 수 있는 수준에서 간단히 다룬다")]),
    num("e34_num_problem", "사칙연산 문제 만들고 해결하기", "자연수의 어림셈", "procedure",
        "실생활 상황으로 사칙연산 문제를 만들어 해결하고 유용성을 인식하는 활동.",
        [tnote(19, "실생활 상황을 이용해 사칙연산 문제를 만들어 해결하게 하고 유용성을 인식하게 한다")]),
    # ---------- 변화와 관계 ----------
    pat("e34_pat_change_rule", "다양한 변화 규칙", "core_concept",
        "찾아 설명하고 수나 식으로 나타내는 변화의 규칙.",
        [std(19, "4수02-01", "다양한 변화 규칙을 찾아 설명한다는 진술")]),
    pat("e34_pat_rule_expression", "규칙을 수나 식으로 나타내기", "procedure",
        "찾은 변화 규칙을 수나 식으로 나타내는 활동.",
        [std(19, "4수02-01", "그 규칙을 수나 식으로 나타낼 수 있다는 진술")],
        notes="혼합 계산식, 일반항을 나타낸 식 등을 이용해야 하는 복잡한 문제는 다루지 않는다(printed p. 19)."),
    pat("e34_pat_calc_array", "계산식의 배열", "representation",
        "다양한 규칙과 수의 성질을 탐구할 수 있는 계산식의 배열.",
        [std(19, "4수02-02", "계산식의 배열에서 규칙을 찾는다는 진술"),
         note(19, "다양한 규칙을 찾을 수 있는 계산식의 배열, 수의 성질을 탐구할 수 있는 배열을 다룬다")]),
    pat("e34_pat_calc_rule", "계산식 배열에서 규칙 찾기", "procedure",
        "계산식의 배열에서 계산 결과의 규칙을 찾는 활동.",
        [std(19, "4수02-02", "계산식의 배열에서 규칙을 찾는다는 진술")]),
    pat("e34_pat_predict", "계산 결과 추측하기", "procedure",
        "찾은 규칙으로 계산 결과를 추측하는 활동.",
        [std(19, "4수02-02", "계산 결과를 추측할 수 있다는 진술")]),
    pat("e34_pat_verify", "추측한 규칙 검토하기", "procedure",
        "추측한 규칙을 배열에 적용해 보는 등 다양한 방법으로 규칙이 옳은지 스스로 검토하는 활동.",
        [tnote(20, "추측한 규칙을 배열에 적용해 보는 등 다양한 방법으로 규칙이 옳은지 검토하게 할 수 있다")]),
    pat("e34_pat_equivalence", "동치 관계", "core_concept",
        "크기가 같은 두 양의 관계.",
        [std(19, "4수02-03", "등호를 사용하여 크기가 같은 두 양의 관계를 식으로 나타낸다는 진술"),
         note(19, "등호의 의미를 토대로 동치 관계를 이해하게 한다")],
        notes="동치 관계는 두 자리 수의 범위에서 다룬다(printed p. 20)."),
    pat("e34_pat_equal_expr", "등호로 크기가 같은 두 양 나타내기", "procedure",
        "등호를 사용하여 크기가 같은 두 양의 관계를 식으로 나타내는 활동.",
        [std(19, "4수02-03", "등호를 사용하여 식으로 나타낼 수 있다는 진술")]),
    pat("e34_pat_judge", "주어진 식이 옳은지 판단하기", "procedure",
        "구체물, 그림, 수 감각과 연산의 성질을 이용해 등호가 사용된 식이 옳은지 판단하는 활동.",
        [note(19, "구체물, 그림 등을 사용하여 주어진 식이 옳은지 판단하는 활동으로 동치 관계를 이해하게 한다"),
         tnote(20, "수 감각이나 직관적으로 이해한 연산의 성질로 두 양이 서로 같은지 비교하게 할 수 있다")]),
    # ---------- 도형과 측정: 도형의 기초 ----------
    geo("e34_geo_line", "직선", "도형의 기초", "term",
        "곧게 뻗은 선을 가리키는 공식 용어.",
        [term(22, "직선"), std(20, "4수03-01", "직선, 선분, 반직선을 이해하고 구별한다는 진술")]),
    geo("e34_geo_segment", "선분", "도형의 기초", "term",
        "두 점을 곧게 이은 선을 가리키는 공식 용어.",
        [term(22, "선분"), std(20, "4수03-01", "직선, 선분, 반직선을 이해하고 구별한다는 진술")]),
    geo("e34_geo_ray", "반직선", "도형의 기초", "term",
        "한 점에서 한쪽으로 곧게 뻗은 선을 가리키는 공식 용어.",
        [term(22, "반직선"), std(20, "4수03-01", "직선, 선분, 반직선을 이해하고 구별한다는 진술")]),
    geo("e34_geo_line_distinguish", "직선·선분·반직선 구별하기", "도형의 기초", "procedure",
        "직선, 선분, 반직선을 서로 구별하는 활동.",
        [std(20, "4수03-01", "직선, 선분, 반직선을 이해하고 구별할 수 있다는 진술")],
        notes="평가에서는 정확한 정의나 표현보다 서로 구별할 수 있는지에 중점을 둔다(printed p. 22)."),
    geo("e34_geo_angle", "각", "도형의 기초", "core_concept",
        "한 점에서 그은 두 반직선으로 이루어지는 도형.",
        [term(22, "각"), std(20, "4수03-02", "각과 직각을 이해한다는 진술")]),
    geo("e34_geo_angle_vertex", "각의 꼭짓점", "도형의 기초", "term",
        "각의 구성 요소를 가리키는 공식 용어.",
        [term(22, "(각의) 꼭짓점")]),
    geo("e34_geo_angle_side", "각의 변", "도형의 기초", "term",
        "각의 구성 요소를 가리키는 공식 용어.",
        [term(22, "(각의) 변")]),
    geo("e34_geo_right_angle", "직각", "도형의 기초", "term",
        "예각·둔각 구별의 기준이 되는 각.",
        [term(22, "직각"), std(20, "4수03-02", "각과 직각을 이해한다는 진술")]),
    geo("e34_geo_acute", "예각", "도형의 기초", "term",
        "직각과 비교하여 구별하는 각의 종류.",
        [term(22, "예각"), std(20, "4수03-02", "직각과 비교하는 활동으로 예각과 둔각을 구별한다는 진술")]),
    geo("e34_geo_obtuse", "둔각", "도형의 기초", "term",
        "직각과 비교하여 구별하는 각의 종류.",
        [term(22, "둔각"), std(20, "4수03-02", "직각과 비교하는 활동으로 예각과 둔각을 구별한다는 진술")]),
    geo("e34_geo_angle_compare", "직각과 비교하여 예각·둔각 구별하기", "도형의 기초", "procedure",
        "직각과 비교하는 활동으로 예각과 둔각을 구별하는 활동.",
        [std(20, "4수03-02", "직각과 비교하는 활동을 통하여 예각과 둔각을 구별할 수 있다는 진술")]),
    geo("e34_geo_perpendicular", "수직과 수선", "도형의 기초", "term",
        "직선의 수직 관계와 그때의 직선을 가리키는 공식 용어.",
        [term(22, "수직, 수선"), std(20, "4수03-03", "직선의 수직 관계를 이해한다는 진술")]),
    geo("e34_geo_parallel", "평행과 평행선", "도형의 기초", "term",
        "직선의 평행 관계와 그때의 직선을 가리키는 공식 용어.",
        [term(22, "평행, 평행선"), std(20, "4수03-03", "직선의 평행 관계를 이해한다는 진술")]),
    geo("e34_geo_perp_parallel_rel", "직선의 수직 관계와 평행 관계", "도형의 기초", "property",
        "두 직선 사이의 수직 관계와 평행 관계.",
        [std(20, "4수03-03", "직선의 수직 관계와 평행 관계를 이해한다는 진술")]),
    # ---------- 도형과 측정: 평면도형의 이동 ----------
    geo("e34_geo_slide", "밀기", "평면도형의 이동", "sub_concept",
        "구체물이나 평면도형을 이동하는 방법.",
        [std(20, "4수03-04", "밀기, 뒤집기, 돌리기 활동을 통하여 변화를 이해한다는 진술")]),
    geo("e34_geo_flip", "뒤집기", "평면도형의 이동", "sub_concept",
        "구체물이나 평면도형을 이동하는 방법.",
        [std(20, "4수03-04", "밀기, 뒤집기, 돌리기 활동을 통하여 변화를 이해한다는 진술")]),
    geo("e34_geo_turn", "돌리기", "평면도형의 이동", "sub_concept",
        "구체물이나 평면도형을 이동하는 방법.",
        [std(20, "4수03-04", "밀기, 뒤집기, 돌리기 활동을 통하여 변화를 이해한다는 진술")]),
    geo("e34_geo_move_change", "평면도형의 이동에 따른 변화 이해하기", "평면도형의 이동", "procedure",
        "실생활 사례에서 이동에 따른 변화를 추론하고 위치나 방향의 변화를 설명하는 활동.",
        [std(20, "4수03-04", "밀기, 뒤집기, 돌리기 활동을 통하여 그 변화를 이해한다는 진술"),
         note(22, "실생활에서 이동을 활용한 사례를 찾아 변화를 추론하고 설명하게 한다")],
        notes="돌리고 뒤집기, 뒤집고 돌리기 등 복잡한 변화는 지양한다(printed p. 22)."),
    geo("e34_geo_point_move", "평면에서 점의 이동 설명하기", "평면도형의 이동", "procedure",
        "격자를 따라 위·아래·오른쪽·왼쪽으로 움직인 점의 이동을 위치와 방향으로 설명하는 활동.",
        [std(20, "4수03-05", "점의 이동에 대해 위치와 방향을 이용하여 설명할 수 있다는 진술"),
         note(22, "격자를 따라 '~칸', '~cm'를 이동하는 수준에서 다룬다")],
        notes="꼭짓점의 이동으로 평면도형의 이동을 설명하는 활동은 다루지 않는다(printed p. 22)."),
    # ---------- 도형과 측정: 원의 구성 요소 ----------
    geo("e34_geo_circle_center", "원의 중심", "원의 구성 요소", "term",
        "원의 구성 요소를 가리키는 공식 용어.",
        [term(22, "원의 중심"), std(20, "4수03-06", "원의 중심, 반지름, 지름을 이해하고 성질을 안다는 진술")]),
    geo("e34_geo_radius", "반지름", "원의 구성 요소", "term",
        "원의 구성 요소를 가리키는 공식 용어.",
        [term(22, "반지름"), std(20, "4수03-06", "원의 중심, 반지름, 지름을 이해하고 성질을 안다는 진술")]),
    geo("e34_geo_diameter", "지름", "원의 구성 요소", "term",
        "원의 구성 요소를 가리키는 공식 용어.",
        [term(22, "지름"), std(20, "4수03-06", "원의 중심, 반지름, 지름을 이해하고 성질을 안다는 진술")]),
    geo("e34_geo_circle_property", "원의 구성 요소의 성질", "원의 구성 요소", "property",
        "원의 중심, 반지름, 지름이 가지는 성질.",
        [std(20, "4수03-06", "그 성질을 안다는 진술")]),
    geo("e34_geo_compass", "컴퍼스로 원 그리기", "원의 구성 요소", "procedure",
        "컴퍼스를 이용하여 여러 가지 크기의 원을 그리는 활동.",
        [std(20, "4수03-07", "컴퍼스를 이용하여 여러 가지 크기의 원을 그릴 수 있다는 진술"),
         note(22, "원을 그리는 방법을 원의 성질과 연결하여 이해하게 한다")]),
    # ---------- 도형과 측정: 여러 가지 삼각형 ----------
    geo("e34_geo_isosceles", "이등변삼각형", "여러 가지 삼각형", "core_concept",
        "분류 활동을 통하여 이해하는 삼각형.",
        [term(22, "이등변삼각형"), std(20, "4수03-08", "분류 활동을 통하여 이등변삼각형, 정삼각형을 이해한다는 진술")]),
    geo("e34_geo_equilateral", "정삼각형", "여러 가지 삼각형", "core_concept",
        "분류 활동을 통하여 이해하는 삼각형.",
        [term(22, "정삼각형"), std(20, "4수03-08", "분류 활동을 통하여 이등변삼각형, 정삼각형을 이해한다는 진술")]),
    geo("e34_geo_tri_classify", "여러 가지 삼각형 분류하기", "여러 가지 삼각형", "procedure",
        "여러 가지 모양의 삼각형을 분류하는 활동.",
        [std(20, "4수03-08", "여러 가지 모양의 삼각형에 대한 분류 활동이라는 진술"),
         std(20, "4수03-09", "분류 활동을 통하여 직각삼각형, 예각삼각형, 둔각삼각형을 이해한다는 진술")]),
    geo("e34_geo_tri_property", "이등변삼각형·정삼각형의 성질 탐구하기", "여러 가지 삼각형", "procedure",
        "관찰, 실험, 측정 등 귀납적 추론으로 성질을 탐구하고 설명하는 활동.",
        [std(20, "4수03-08", "그 성질을 탐구하고 설명할 수 있다는 진술"),
         tnote(22, "구체적인 관찰, 실험, 측정 등 귀납적 추론을 통해 성질을 이해하게 한다")]),
    geo("e34_geo_right_tri", "직각삼각형", "여러 가지 삼각형", "term",
        "각의 크기에 따라 분류한 삼각형.",
        [term(22, "직각삼각형"), std(20, "4수03-09", "직각삼각형, 예각삼각형, 둔각삼각형을 이해한다는 진술")]),
    geo("e34_geo_acute_tri", "예각삼각형", "여러 가지 삼각형", "term",
        "각의 크기에 따라 분류한 삼각형.",
        [term(22, "예각삼각형"), std(20, "4수03-09", "직각삼각형, 예각삼각형, 둔각삼각형을 이해한다는 진술")]),
    geo("e34_geo_obtuse_tri", "둔각삼각형", "여러 가지 삼각형", "term",
        "각의 크기에 따라 분류한 삼각형.",
        [term(22, "둔각삼각형"), std(20, "4수03-09", "직각삼각형, 예각삼각형, 둔각삼각형을 이해한다는 진술")]),
    # ---------- 도형과 측정: 여러 가지 사각형 ----------
    geo("e34_geo_rect", "직사각형", "여러 가지 사각형", "core_concept",
        "분류 활동을 통하여 이해하는 사각형.",
        [term(22, "직사각형"), std(20, "4수03-10", "분류 활동을 통하여 여러 가지 사각형을 이해한다는 진술")]),
    geo("e34_geo_square", "정사각형", "여러 가지 사각형", "core_concept",
        "분류 활동을 통하여 이해하는 사각형.",
        [term(22, "정사각형"), std(20, "4수03-10", "분류 활동을 통하여 여러 가지 사각형을 이해한다는 진술")]),
    geo("e34_geo_trapezoid", "사다리꼴", "여러 가지 사각형", "core_concept",
        "분류 활동을 통하여 이해하는 사각형.",
        [term(22, "사다리꼴"), std(20, "4수03-10", "분류 활동을 통하여 여러 가지 사각형을 이해한다는 진술")]),
    geo("e34_geo_parallelogram", "평행사변형", "여러 가지 사각형", "core_concept",
        "분류 활동을 통하여 이해하는 사각형.",
        [term(22, "평행사변형"), std(20, "4수03-10", "분류 활동을 통하여 여러 가지 사각형을 이해한다는 진술")]),
    geo("e34_geo_rhombus", "마름모", "여러 가지 사각형", "core_concept",
        "분류 활동을 통하여 이해하는 사각형.",
        [term(22, "마름모"), std(20, "4수03-10", "분류 활동을 통하여 여러 가지 사각형을 이해한다는 진술")]),
    geo("e34_geo_quad_classify", "여러 가지 사각형 분류하기", "여러 가지 사각형", "procedure",
        "여러 가지 모양의 사각형을 분류하는 활동.",
        [std(20, "4수03-10", "여러 가지 모양의 사각형에 대한 분류 활동이라는 진술")]),
    geo("e34_geo_quad_property", "여러 가지 사각형의 성질 탐구하기", "여러 가지 사각형", "procedure",
        "구체적인 조작 활동을 통하여 사각형의 성질을 탐구하고 설명하는 활동.",
        [std(20, "4수03-10", "그 성질을 탐구하고 설명할 수 있다는 진술"),
         tnote(22, "사각형의 성질은 구체적인 조작 활동으로 간단한 것만 다룬다")],
        notes="여러 가지 사각형 사이의 관계는 다루지 않는다(printed p. 22)."),
    # ---------- 도형과 측정: 다각형 ----------
    geo("e34_geo_polygon", "다각형", "다각형", "core_concept",
        "교구를 이용한 조작 활동을 통하여 이해하는 도형.",
        [term(22, "다각형"), std(21, "4수03-11", "다각형과 정다각형을 이해한다는 진술"),
         note(22, "도형판, 모양 조각 등의 교구를 이용한 조작 활동을 통해 이해하게 한다")]),
    geo("e34_geo_regular_polygon", "정다각형", "다각형", "core_concept",
        "교구를 이용한 조작 활동을 통하여 이해하는 도형.",
        [term(22, "정다각형"), std(21, "4수03-11", "다각형과 정다각형을 이해한다는 진술")]),
    geo("e34_geo_diagonal", "대각선", "다각형", "term",
        "다각형의 구성 요소를 가리키는 공식 용어.",
        [term(22, "대각선")]),
    geo("e34_geo_fill_shapes", "도형으로 모양 만들거나 채우기", "다각형", "procedure",
        "주어진 도형을 이용하여 여러 가지 모양을 만들거나 채우고 설명하는 활동.",
        [std(21, "4수03-12", "주어진 도형을 이용하여 모양을 만들거나 채우고 설명할 수 있다는 진술"),
         note(22, "다양한 교구와 공학 도구 등을 이용한 구체적인 활동으로 만들거나 채울 수 있다")]),
    # ---------- 도형과 측정: 시각과 시간 ----------
    geo("e34_meas_second", "초", "시각과 시간", "term",
        "시각과 시간의 공식 단위 용어.",
        [term(22, "초"), std(21, "4수03-13", "1분과 1초의 관계를 이해한다는 진술")]),
    geo("e34_meas_min_sec_rel", "1분과 1초의 관계", "시각과 시간", "property",
        "1분과 1초 사이의 관계.",
        [std(21, "4수03-13", "1분과 1초의 관계를 이해한다는 진술")]),
    geo("e34_meas_read_seconds", "초 단위까지 시각 읽기", "시각과 시간", "procedure",
        "초 단위까지 시각을 읽는 활동.",
        [std(21, "4수03-13", "초 단위까지 시각을 읽을 수 있다는 진술")]),
    geo("e34_meas_time_addsub", "시간의 덧셈과 뺄셈", "시각과 시간", "procedure",
        "실생활 문제 상황과 연결하여 초 단위까지의 시간의 덧셈과 뺄셈을 하는 활동.",
        [std(21, "4수03-14", "초 단위까지의 시간의 덧셈과 뺄셈을 할 수 있다는 진술")]),
    # ---------- 도형과 측정: 길이 ----------
    geo("e34_meas_mm", "길이 단위 1mm", "길이", "term",
        "길이의 표준 단위 1mm.",
        [term(22, "mm"), std(21, "4수03-15", "길이 단위 1mm와 1km를 안다는 진술")]),
    geo("e34_meas_km", "길이 단위 1km", "길이", "term",
        "길이의 표준 단위 1km.",
        [term(22, "km"), std(21, "4수03-15", "길이 단위 1mm와 1km를 안다는 진술")]),
    geo("e34_meas_length_measure", "mm·km로 길이 측정하고 어림하기", "길이", "procedure",
        "1mm와 1km를 이용하여 길이를 측정하고 어림하며 수학의 유용성을 인식하는 활동.",
        [std(21, "4수03-15", "이를 이용하여 길이를 측정하고 어림하며 유용성을 인식한다는 진술")]),
    geo("e34_meas_length_rel", "길이 단위 사이의 관계와 표현", "길이", "property",
        "1cm와 1mm, 1km와 1m의 관계를 이해하고 길이를 다양하게 표현.",
        [std(21, "4수03-16", "단위 관계를 이해하고 '몇 cm 몇 mm', '몇 km 몇 m' 등으로 표현한다는 진술")],
        notes="1km와 1cm의 관계 등 지나친 단위 환산은 다루지 않는다(printed p. 23)."),
    # ---------- 도형과 측정: 들이 ----------
    geo("e34_meas_liter", "들이 단위 1L", "들이", "term",
        "들이의 표준 단위 1L.",
        [term(22, "L"), std(21, "4수03-17", "들이 단위 1L와 1mL를 안다는 진술")]),
    geo("e34_meas_ml", "들이 단위 1mL", "들이", "term",
        "들이의 표준 단위 1mL.",
        [term(22, "mL"), std(21, "4수03-17", "들이 단위 1L와 1mL를 안다는 진술")]),
    geo("e34_meas_capacity_measure", "들이 측정하고 어림하기", "들이", "procedure",
        "1L와 1mL를 이용하여 들이를 측정하고 어림하며 수학의 유용성을 인식하는 활동.",
        [std(21, "4수03-17", "이를 이용하여 들이를 측정하고 어림한다는 진술"),
         tnote(23, "들이, 무게의 표준 단위를 도입하기 전에 표준 단위의 필요성을 알게 한다")]),
    geo("e34_meas_capacity_rel", "들이 단위 사이의 관계와 표현", "들이", "property",
        "1L와 1mL의 관계를 이해하고 들이를 '몇 L 몇 mL'와 '몇 mL'로 표현.",
        [std(21, "4수03-18", "1L와 1mL의 관계를 이해하고 표현한다는 진술")]),
    geo("e34_meas_capacity_addsub", "들이의 덧셈과 뺄셈", "들이", "procedure",
        "실생활 문제 상황과 연결하여 들이의 덧셈과 뺄셈을 하는 활동.",
        [std(21, "4수03-19", "들이의 덧셈과 뺄셈을 할 수 있다는 진술")]),
    # ---------- 도형과 측정: 무게 ----------
    geo("e34_meas_gram", "무게 단위 1g", "무게", "term",
        "무게를 나타낼 때 사용하는 단위 1g.",
        [term(22, "g"), std(21, "4수03-20", "단위 1g과 1kg을 안다는 진술")]),
    geo("e34_meas_kg", "무게 단위 1kg", "무게", "term",
        "무게를 나타낼 때 사용하는 단위 1kg.",
        [term(22, "kg"), std(21, "4수03-20", "단위 1g과 1kg을 안다는 진술")]),
    geo("e34_meas_ton", "무게 단위 1t", "무게", "term",
        "실생활에서 무게를 나타낼 때 사용하는 단위 1t.",
        [term(22, "t"), std(21, "4수03-22", "단위 1t을 알고 1t과 1kg의 관계를 이해한다는 진술")]),
    geo("e34_meas_weight_measure", "무게 측정하고 어림하기", "무게", "procedure",
        "1g과 1kg을 이용하여 무게를 측정하고 어림하며 수학의 유용성을 인식하는 활동.",
        [std(21, "4수03-20", "이를 이용하여 무게를 측정하고 어림한다는 진술"),
         note(22, "초등학교에서는 무게와 질량의 개념을 엄밀하게 구분하지 않는다")]),
    geo("e34_meas_weight_rel", "무게 단위 사이의 관계와 표현", "무게", "property",
        "1kg과 1g, 1t과 1kg의 관계를 이해하고 무게를 표현.",
        [std(21, "4수03-21", "1kg과 1g의 관계를 이해하고 표현한다는 진술"),
         std(21, "4수03-22", "1t과 1kg의 관계를 이해한다는 진술")],
        notes="1t과 1g의 관계 등 지나친 단위 환산은 다루지 않는다(printed p. 23)."),
    geo("e34_meas_weight_addsub", "무게의 덧셈과 뺄셈", "무게", "procedure",
        "실생활 문제 상황과 연결하여 무게의 덧셈과 뺄셈을 하는 활동.",
        [std(21, "4수03-23", "무게의 덧셈과 뺄셈을 할 수 있다는 진술")]),
    # ---------- 도형과 측정: 각도 ----------
    geo("e34_meas_degree", "각의 크기 단위 1도(°)", "각도", "term",
        "각의 크기의 단위 1도.",
        [term(22, "도(°)"), std(21, "4수03-24", "각의 크기의 단위인 1도를 안다는 진술")]),
    geo("e34_meas_protractor", "각도기로 각의 크기 측정하고 어림하기", "각도", "procedure",
        "각도기를 이용하여 각의 크기를 측정하고 어림하는 활동.",
        [std(21, "4수03-24", "각도기를 이용하여 각의 크기를 측정하고 어림할 수 있다는 진술")]),
    geo("e34_meas_angle_sum", "삼각형과 사각형의 내각 크기의 합 추론하기", "각도", "procedure",
        "여러 가지 방법으로 내각의 크기의 합을 추론하고 추론 과정을 설명하는 활동.",
        [std(21, "4수03-25", "내각의 크기의 합을 추론하고 자신의 추론 과정을 설명할 수 있다는 진술")]),
    geo("e34_meas_sense", "시간·길이·들이·무게·각도에 대한 양감", "각도", "sub_concept",
        "실제로 재거나 어림하는 측정 활동을 통해 기르는 양감.",
        [tnote(23, "실제로 재거나 어림하는 측정 활동을 통하여 양감을 기르게 한다")]),
    # ---------- 자료와 가능성 ----------
    dat("e34_data_collect", "자료 수집하기", "procedure",
        "설문조사, 실험과 관찰, 공공 자료의 활용 등으로 자료를 직접 수집하는 활동.",
        [std(23, "4수04-01", "자료를 수집하여 그래프로 나타낸다는 진술"),
         tnote(23, "간단한 설문조사, 실험과 관찰, 공공 자료의 활용 등을 통해 자료를 직접 수집하게 한다")]),
    dat("e34_data_pictograph", "그림그래프", "term",
        "자료를 그림으로 나타내는 공식 그래프 용어.",
        [term(23, "그림그래프"), std(23, "4수04-01", "그림그래프나 막대그래프로 나타내고 해석한다는 진술")]),
    dat("e34_data_bar", "막대그래프", "term",
        "자료를 막대로 나타내는 공식 그래프 용어.",
        [term(23, "막대그래프"), std(23, "4수04-01", "그림그래프나 막대그래프로 나타내고 해석한다는 진술")]),
    dat("e34_data_line", "꺾은선그래프", "term",
        "자료를 꺾은선으로 나타내는 공식 그래프 용어.",
        [term(23, "꺾은선그래프"), std(23, "4수04-02", "꺾은선그래프로 나타내고 해석한다는 진술")]),
    dat("e34_data_pictograph_draw", "그림그래프로 나타내고 해석하기", "procedure",
        "자료를 그림그래프로 나타내고 해석하는 활동.",
        [std(23, "4수04-01", "그림그래프나 막대그래프로 나타내고 해석할 수 있다는 진술")],
        notes="항목의 이름과 수량의 단위를 명확히 인식하고 그림이 나타내는 단위를 적절히 선택하게 한다(printed p. 23)."),
    dat("e34_data_bar_draw", "막대그래프로 나타내고 해석하기", "procedure",
        "자료를 막대그래프로 나타내고 해석하는 활동.",
        [std(23, "4수04-01", "그림그래프나 막대그래프로 나타내고 해석할 수 있다는 진술")],
        notes="가로축과 세로축이 무엇을 나타내는지 확인하고 눈금 한 칸의 크기를 적절히 선택하게 한다(printed p. 24)."),
    dat("e34_data_line_draw", "꺾은선그래프로 나타내고 해석하기", "procedure",
        "자료를 꺾은선그래프로 나타내고 해석하는 활동.",
        [std(23, "4수04-02", "꺾은선그래프로 나타내고 해석할 수 있다는 진술")]),
    dat("e34_data_choose_graph", "목적에 맞는 그래프 선택하기", "procedure",
        "자료의 특성에 따라 목적에 맞는 그래프를 선택하는 활동.",
        [note(23, "크기 비교는 막대그래프, 시간에 따른 변화 경향은 꺾은선그래프가 편리함을 알고 적절한 그래프를 선택하게 한다")]),
    dat("e34_data_inquiry", "통계적 탐구 과정 경험하기", "procedure",
        "탐구 문제 해결을 위해 자료를 수집, 정리하고 그래프로 나타내어 해석하는 일련의 과정.",
        [std(23, "4수04-03", "탐구 문제를 해결하기 위해 자료를 수집, 정리하여 그래프로 나타내고 해석한다는 진술"),
         note(23, "자료를 수집, 정리하고 그래프로 나타내어 해석하는 일련의 과정을 직접 경험하게 한다")]),
    dat("e34_data_critical", "그래프 표현의 적절성 판단하기", "procedure",
        "자료 수집의 목적과 자료의 특성에 맞는 그래프로 표현되었는지 비판적으로 판단하는 활동.",
        [tnote(24, "목적과 특성에 맞는 그래프로 적절히 표현되었는지 비판적으로 판단하게 할 수 있다")]),
]

EDGE_DEFS = [
    # 수와 연산: 큰 수
    ("e34_num_big", "e34_num_big_place", "contains", "high", "printed p. 17; [4수01-01]", "큰 수 이해에 자릿값과 위치적 기수법이 포함된다", ""),
    ("e34_num_big_need", "e34_num_big", "used_in", "high", "printed p. 18 적용 시 고려 사항", "조사 활동으로 큰 수의 필요성을 인식하게 한다", ""),
    ("e34_num_big_place", "e34_num_big_compare", "prerequisite_for", "medium", "printed p. 17; [4수01-01]~[4수01-02]", "자릿값 이해 후 수의 계열과 크기 비교로 이어지는 성취기준 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e12_num_place_value", "e34_num_big_place", "prerequisite_for", "medium", "printed p. 11, 17", "네 자리 이하 수의 자릿값에서 다섯 자리 이상으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e12_num_compare", "e34_num_big_compare", "prerequisite_for", "medium", "printed p. 11, 17", "네 자리 이하 수의 크기 비교에서 다섯 자리 이상으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    # 수와 연산: 덧셈·뺄셈·곱셈
    ("e12_addsub_two_digit_calc", "e34_num_addsub3", "prerequisite_for", "medium", "printed p. 11, 17", "두 자리 수 범위에서 세 자리 수 범위로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e12_single_digit_mul", "e34_num_mul_multi", "prerequisite_for", "medium", "printed p. 11, 17", "한 자리 수의 곱셈에서 두·세 자리 수 곱셈으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    # 수와 연산: 나눗셈
    ("e34_num_div", "e34_num_quotient", "contains", "high", "printed p. 17; [4수01-06]", "나눗셈에서 몫의 의미를 안다", ""),
    ("e34_num_div", "e34_num_remainder", "contains", "high", "printed p. 17; [4수01-06]", "나눗셈에서 나머지의 의미를 안다", ""),
    ("e34_num_div", "e34_num_div_symbol", "represented_by", "high", "printed p. 18 용어와 기호", "나눗셈은 기호 ÷로 나타낸다", ""),
    ("e34_num_mul_multi", "e34_num_mul_div_rel", "used_in", "high", "printed p. 17; [4수01-05]", "곱셈과 나눗셈의 관계 이해에 곱셈이 쓰인다", ""),
    ("e34_num_div", "e34_num_mul_div_rel", "used_in", "high", "printed p. 17; [4수01-05]", "곱셈과 나눗셈의 관계 이해에 나눗셈이 쓰인다", ""),
    ("e34_num_div", "e34_num_div1_calc", "prerequisite_for", "high", "printed p. 17; [4수01-05]~[4수01-06]", "나눗셈의 의미를 알고 계산으로 이어지는 진술 구조", ""),
    ("e34_num_div1_calc", "e34_num_div2_calc", "prerequisite_for", "medium", "printed p. 17; [4수01-06]~[4수01-07]", "나누는 수가 한 자리 수에서 두 자리 수로 확장", "성취기준 배열 순서에서 추론한 관계다."),
    ("e34_num_mul_div_rel", "e34_num_div_check", "used_in", "high", "printed p. 18 적용 시 고려 사항", "나눗셈식을 곱셈식으로 나타내는 검산 활동", ""),
    ("e34_num_divisible", "e34_num_div1_calc", "related_to", "high", "printed p. 18 성취기준 해설", "나누어떨어지는 경우와 그렇지 않은 경우를 포함해 다룬다", ""),
    # 수와 연산: 어림셈
    ("e34_num_estimation", "e34_num_problem", "related_to", "high", "printed p. 19 적용 시 고려 사항", "어림셈과 문제 만들기 모두 사칙연산 상황 활동으로 제시된다", ""),
    # 수와 연산: 분수
    ("e34_num_partition", "e34_num_fraction", "prerequisite_for", "high", "printed p. 17; [4수01-09]", "양의 등분할을 통하여 분수를 도입한다", ""),
    ("e34_num_fraction_need", "e34_num_fraction", "used_in", "high", "printed p. 18 성취기준 해설", "1보다 작은 양의 표현으로 분수의 필요성을 인식하게 한다", ""),
    ("e34_num_fraction", "e34_num_denominator", "contains", "high", "printed p. 18 성취기준 해설", "분수 도입에서 분모를 사용한다", ""),
    ("e34_num_fraction", "e34_num_numerator", "contains", "high", "printed p. 18 성취기준 해설", "분수 도입에서 분자를 사용한다", ""),
    ("e34_num_fraction", "e34_num_unit_fraction", "contains", "high", "printed p. 17; [4수01-10]", "단위분수는 분수의 한 종류다", ""),
    ("e34_num_fraction", "e34_num_proper", "contains", "high", "printed p. 17; [4수01-10]", "진분수는 분수의 한 종류다", ""),
    ("e34_num_fraction", "e34_num_improper", "contains", "high", "printed p. 17; [4수01-10]", "가분수는 분수의 한 종류다", ""),
    ("e34_num_fraction", "e34_num_mixed", "contains", "high", "printed p. 17; [4수01-10]", "대분수는 분수의 한 종류다", ""),
    ("e34_num_unit_fraction", "e34_num_fraction_types_rel", "used_in", "high", "printed p. 17; [4수01-10]", "분수 종류 사이의 관계 이해에 쓰인다", ""),
    ("e34_num_fraction", "e34_num_fraction_compare", "prerequisite_for", "high", "printed p. 17; [4수01-09]~[4수01-11]", "분수를 이해하고 크기 비교로 이어지는 진술 구조", ""),
    ("e34_num_fraction", "e34_num_fraction_addsub", "prerequisite_for", "high", "printed p. 17~18; [4수01-09], [4수01-15]", "분수 이해를 바탕으로 분모가 같은 분수의 덧셈과 뺄셈을 다룬다", ""),
    ("e12_addsub_two_digit_calc", "e34_num_fraction_addsub", "related_to", "medium", "printed p. 11, 18", "자연수 덧셈·뺄셈 경험과 연결되는 분수 연산", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    # 수와 연산: 소수
    ("e34_num_decimal1", "e34_num_decimal", "contains", "high", "printed p. 17; [4수01-12]", "소수 한 자리 수는 소수 이해의 시작이다", ""),
    ("e34_num_fraction", "e34_num_decimal1", "prerequisite_for", "high", "printed p. 17; [4수01-12]", "분모가 10인 진분수와 연결하여 소수 한 자리 수를 이해한다", ""),
    ("e34_num_decimal", "e34_num_decimal_point", "represented_by", "high", "printed p. 18 용어와 기호", "소수는 소수점 기호로 나타낸다", ""),
    ("e34_num_decimal1", "e34_num_decimal23", "prerequisite_for", "high", "printed p. 17~18; [4수01-12]~[4수01-13]", "소수 한 자리 수에서 두·세 자리 수로 확장하는 진술 구조", ""),
    ("e12_num_place_value", "e34_num_decimal23", "used_in", "high", "printed p. 18; [4수01-13]", "자릿값의 원리를 바탕으로 소수 두·세 자리 수를 이해한다", ""),
    ("e34_num_decimal", "e34_num_decimal_compare", "prerequisite_for", "high", "printed p. 18; [4수01-12]~[4수01-14]", "소수를 이해하고 크기 비교로 이어지는 진술 구조", ""),
    ("e34_num_decimal_need", "e34_num_decimal", "used_in", "high", "printed p. 19 적용 시 고려 사항", "실생활 사례로 소수의 필요성을 인식하게 한다", ""),
    ("e34_num_decimal", "e34_num_decimal_addsub", "prerequisite_for", "high", "printed p. 18; [4수01-16]", "소수 이해를 바탕으로 소수의 덧셈과 뺄셈을 다룬다", ""),
    ("e34_num_natural", "e34_num_decimal", "related_to", "medium", "printed p. 18 용어와 기호", "자연수와 소수가 같은 용어 목록에서 도입된다", ""),
    # 변화와 관계
    ("e12_pat_rule", "e34_pat_change_rule", "prerequisite_for", "medium", "printed p. 13, 19", "규칙 찾기에서 변화 규칙을 수나 식으로 나타내는 단계로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_pat_change_rule", "e34_pat_rule_expression", "prerequisite_for", "high", "printed p. 19; [4수02-01]", "규칙을 찾아 설명하고 수나 식으로 나타낸다는 진술 구조", ""),
    ("e34_pat_calc_array", "e34_pat_calc_rule", "used_in", "high", "printed p. 19; [4수02-02]", "계산식의 배열에서 규칙을 찾는다", ""),
    ("e34_pat_calc_rule", "e34_pat_predict", "prerequisite_for", "high", "printed p. 19; [4수02-02]", "규칙을 찾고 계산 결과를 추측한다는 진술 구조", ""),
    ("e34_pat_predict", "e34_pat_verify", "prerequisite_for", "high", "printed p. 20 적용 시 고려 사항", "추측한 규칙을 적용해 옳은지 검토하게 한다", ""),
    ("e12_equal_both_sides", "e34_pat_equivalence", "prerequisite_for", "high", "printed p. 19 성취기준 해설", "등호의 의미를 토대로 동치 관계를 이해하게 한다", ""),
    ("e34_pat_equivalence", "e34_pat_equal_expr", "used_in", "high", "printed p. 19; [4수02-03]", "크기가 같은 두 양의 관계를 등호를 사용한 식으로 나타낸다", ""),
    ("e34_pat_judge", "e34_pat_equivalence", "used_in", "high", "printed p. 19 성취기준 해설", "식이 옳은지 판단하는 활동으로 동치 관계를 이해하게 한다", ""),
    # 도형과 측정: 도형의 기초
    ("e34_geo_line", "e34_geo_line_distinguish", "used_in", "high", "printed p. 20; [4수03-01]", "직선, 선분, 반직선을 구별한다", ""),
    ("e34_geo_segment", "e34_geo_line_distinguish", "used_in", "high", "printed p. 20; [4수03-01]", "직선, 선분, 반직선을 구별한다", ""),
    ("e34_geo_ray", "e34_geo_line_distinguish", "used_in", "high", "printed p. 20; [4수03-01]", "직선, 선분, 반직선을 구별한다", ""),
    ("e34_geo_angle", "e34_geo_angle_vertex", "contains", "high", "printed p. 22 용어와 기호", "각의 꼭짓점은 각의 구성 요소다", ""),
    ("e34_geo_angle", "e34_geo_angle_side", "contains", "high", "printed p. 22 용어와 기호", "각의 변은 각의 구성 요소다", ""),
    ("e34_geo_ray", "e34_geo_angle", "used_in", "medium", "printed p. 20; [4수03-01]~[4수03-02]", "반직선 이해가 각 이해로 이어지는 성취기준 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e34_geo_right_angle", "e34_geo_angle_compare", "used_in", "high", "printed p. 20; [4수03-02]", "직각과 비교하는 활동으로 예각과 둔각을 구별한다", ""),
    ("e34_geo_angle_compare", "e34_geo_acute", "used_in", "high", "printed p. 20; [4수03-02]", "비교 활동으로 예각을 구별한다", ""),
    ("e34_geo_angle_compare", "e34_geo_obtuse", "used_in", "high", "printed p. 20; [4수03-02]", "비교 활동으로 둔각을 구별한다", ""),
    ("e34_geo_perpendicular", "e34_geo_perp_parallel_rel", "used_in", "high", "printed p. 20; [4수03-03]", "직선의 수직 관계를 이해한다", ""),
    ("e34_geo_parallel", "e34_geo_perp_parallel_rel", "used_in", "high", "printed p. 20; [4수03-03]", "직선의 평행 관계를 이해한다", ""),
    ("e34_geo_line", "e34_geo_perp_parallel_rel", "used_in", "high", "printed p. 20; [4수03-03]", "직선 사이의 수직·평행 관계를 다룬다", ""),
    # 도형과 측정: 평면도형의 이동
    ("e34_geo_slide", "e34_geo_move_change", "used_in", "high", "printed p. 20; [4수03-04]", "밀기 활동을 통하여 변화를 이해한다", ""),
    ("e34_geo_flip", "e34_geo_move_change", "used_in", "high", "printed p. 20; [4수03-04]", "뒤집기 활동을 통하여 변화를 이해한다", ""),
    ("e34_geo_turn", "e34_geo_move_change", "used_in", "high", "printed p. 20; [4수03-04]", "돌리기 활동을 통하여 변화를 이해한다", ""),
    ("e12_geo_position_words", "e34_geo_point_move", "prerequisite_for", "medium", "printed p. 13, 20", "위치와 방향으로 말하기에서 점의 이동 설명으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    # 도형과 측정: 원
    ("e12_geo_circle", "e34_geo_circle_center", "prerequisite_for", "medium", "printed p. 13, 20", "원의 직관적 이해에서 구성 요소 이해로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_geo_circle_center", "e34_geo_circle_property", "used_in", "high", "printed p. 20; [4수03-06]", "원의 중심의 성질을 안다", ""),
    ("e34_geo_radius", "e34_geo_circle_property", "used_in", "high", "printed p. 20; [4수03-06]", "반지름의 성질을 안다", ""),
    ("e34_geo_diameter", "e34_geo_circle_property", "used_in", "high", "printed p. 20; [4수03-06]", "지름의 성질을 안다", ""),
    ("e34_geo_circle_property", "e34_geo_compass", "used_in", "high", "printed p. 22 성취기준 해설", "원을 그리는 방법을 원의 성질과 연결하여 이해하게 한다", ""),
    # 도형과 측정: 삼각형·사각형·다각형
    ("e34_geo_tri_classify", "e34_geo_isosceles", "used_in", "high", "printed p. 20; [4수03-08]", "분류 활동을 통하여 이등변삼각형을 이해한다", ""),
    ("e34_geo_tri_classify", "e34_geo_equilateral", "used_in", "high", "printed p. 20; [4수03-08]", "분류 활동을 통하여 정삼각형을 이해한다", ""),
    ("e34_geo_tri_classify", "e34_geo_right_tri", "used_in", "high", "printed p. 20; [4수03-09]", "분류 활동을 통하여 직각삼각형을 이해한다", ""),
    ("e34_geo_tri_classify", "e34_geo_acute_tri", "used_in", "high", "printed p. 20; [4수03-09]", "분류 활동을 통하여 예각삼각형을 이해한다", ""),
    ("e34_geo_tri_classify", "e34_geo_obtuse_tri", "used_in", "high", "printed p. 20; [4수03-09]", "분류 활동을 통하여 둔각삼각형을 이해한다", ""),
    ("e12_geo_triangle", "e34_geo_tri_classify", "prerequisite_for", "medium", "printed p. 13, 20", "삼각형의 직관적 이해에서 분류 활동으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_geo_isosceles", "e34_geo_tri_property", "used_in", "high", "printed p. 20; [4수03-08]", "이등변삼각형의 성질을 탐구하고 설명한다", ""),
    ("e34_geo_equilateral", "e34_geo_tri_property", "used_in", "high", "printed p. 20; [4수03-08]", "정삼각형의 성질을 탐구하고 설명한다", ""),
    ("e34_geo_right_angle", "e34_geo_right_tri", "used_in", "high", "printed p. 20; [4수03-09]", "직각을 기준으로 직각삼각형을 이해한다", ""),
    ("e34_geo_acute", "e34_geo_acute_tri", "used_in", "high", "printed p. 20; [4수03-09]", "예각을 기준으로 예각삼각형을 이해한다", ""),
    ("e34_geo_obtuse", "e34_geo_obtuse_tri", "used_in", "high", "printed p. 20; [4수03-09]", "둔각을 기준으로 둔각삼각형을 이해한다", ""),
    ("e34_geo_quad_classify", "e34_geo_rect", "used_in", "high", "printed p. 20; [4수03-10]", "분류 활동을 통하여 직사각형을 이해한다", ""),
    ("e34_geo_quad_classify", "e34_geo_square", "used_in", "high", "printed p. 20; [4수03-10]", "분류 활동을 통하여 정사각형을 이해한다", ""),
    ("e34_geo_quad_classify", "e34_geo_trapezoid", "used_in", "high", "printed p. 20; [4수03-10]", "분류 활동을 통하여 사다리꼴을 이해한다", ""),
    ("e34_geo_quad_classify", "e34_geo_parallelogram", "used_in", "high", "printed p. 20; [4수03-10]", "분류 활동을 통하여 평행사변형을 이해한다", ""),
    ("e34_geo_quad_classify", "e34_geo_rhombus", "used_in", "high", "printed p. 20; [4수03-10]", "분류 활동을 통하여 마름모를 이해한다", ""),
    ("e12_geo_quadrilateral", "e34_geo_quad_classify", "prerequisite_for", "medium", "printed p. 13, 20", "사각형의 직관적 이해에서 분류 활동으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_geo_parallel", "e34_geo_parallelogram", "used_in", "medium", "printed p. 20; [4수03-03], [4수03-10]", "평행 관계 이해가 평행사변형·사다리꼴 이해에 쓰인다", "문서가 직접 연결을 말하지 않으므로 medium을 유지한다."),
    ("e34_geo_rect", "e34_geo_quad_property", "used_in", "high", "printed p. 20; [4수03-10]", "여러 가지 사각형의 성질을 탐구하고 설명한다", ""),
    ("e34_geo_polygon", "e34_geo_regular_polygon", "contains", "high", "printed p. 21; [4수03-11]", "정다각형은 다각형의 한 종류다", ""),
    ("e34_geo_polygon", "e34_geo_diagonal", "contains", "high", "printed p. 22 용어와 기호", "대각선은 다각형의 구성 요소다", ""),
    ("e12_geo_make_plane", "e34_geo_fill_shapes", "prerequisite_for", "medium", "printed p. 13, 21", "평면 모양 만들기에서 모양 만들거나 채우기로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    # 도형과 측정: 시각과 시간
    ("e12_meas_minute_term", "e34_meas_min_sec_rel", "used_in", "high", "printed p. 21; [4수03-13]", "1분과 1초의 관계를 이해한다", ""),
    ("e34_meas_second", "e34_meas_min_sec_rel", "used_in", "high", "printed p. 21; [4수03-13]", "1분과 1초의 관계를 이해한다", ""),
    ("e34_meas_min_sec_rel", "e34_meas_read_seconds", "prerequisite_for", "high", "printed p. 21; [4수03-13]", "관계를 이해하고 초 단위까지 시각을 읽는다는 진술 구조", ""),
    ("e12_meas_read_time", "e34_meas_read_seconds", "prerequisite_for", "medium", "printed p. 14, 21", "몇 시 몇 분 읽기에서 초 단위 읽기로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_meas_read_seconds", "e34_meas_time_addsub", "prerequisite_for", "medium", "printed p. 21; [4수03-13]~[4수03-14]", "초 단위 시각 읽기에서 시간의 덧셈과 뺄셈으로 확장", "성취기준 배열 순서에서 추론한 관계다."),
    # 도형과 측정: 길이·들이·무게·각도
    ("e12_meas_cm", "e34_meas_mm", "prerequisite_for", "medium", "printed p. 14, 21", "cm·m 단위에서 mm·km 단위로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e12_meas_m", "e34_meas_km", "prerequisite_for", "medium", "printed p. 14, 21", "cm·m 단위에서 mm·km 단위로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_meas_mm", "e34_meas_length_measure", "used_in", "high", "printed p. 21; [4수03-15]", "1mm를 이용하여 길이를 측정하고 어림한다", ""),
    ("e34_meas_km", "e34_meas_length_measure", "used_in", "high", "printed p. 21; [4수03-15]", "1km를 이용하여 길이를 측정하고 어림한다", ""),
    ("e34_meas_mm", "e34_meas_length_rel", "used_in", "high", "printed p. 21; [4수03-16]", "1cm와 1mm의 관계를 이해하고 표현한다", ""),
    ("e34_meas_km", "e34_meas_length_rel", "used_in", "high", "printed p. 21; [4수03-16]", "1km와 1m의 관계를 이해하고 표현한다", ""),
    ("e34_meas_liter", "e34_meas_capacity_measure", "used_in", "high", "printed p. 21; [4수03-17]", "1L를 이용하여 들이를 측정하고 어림한다", ""),
    ("e34_meas_ml", "e34_meas_capacity_measure", "used_in", "high", "printed p. 21; [4수03-17]", "1mL를 이용하여 들이를 측정하고 어림한다", ""),
    ("e34_meas_liter", "e34_meas_capacity_rel", "used_in", "high", "printed p. 21; [4수03-18]", "1L와 1mL의 관계를 이해하고 표현한다", ""),
    ("e34_meas_capacity_rel", "e34_meas_capacity_addsub", "prerequisite_for", "medium", "printed p. 21; [4수03-18]~[4수03-19]", "단위 관계 이해에서 들이의 덧셈과 뺄셈으로 이어지는 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e12_meas_compare_capacity", "e34_meas_capacity_measure", "prerequisite_for", "medium", "printed p. 14, 21", "들이의 직접 비교에서 표준 단위 측정으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_meas_gram", "e34_meas_weight_measure", "used_in", "high", "printed p. 21; [4수03-20]", "1g을 이용하여 무게를 측정하고 어림한다", ""),
    ("e34_meas_kg", "e34_meas_weight_measure", "used_in", "high", "printed p. 21; [4수03-20]", "1kg을 이용하여 무게를 측정하고 어림한다", ""),
    ("e34_meas_kg", "e34_meas_weight_rel", "used_in", "high", "printed p. 21; [4수03-21]", "1kg과 1g의 관계를 이해하고 표현한다", ""),
    ("e34_meas_ton", "e34_meas_weight_rel", "used_in", "high", "printed p. 21; [4수03-22]", "1t과 1kg의 관계를 이해한다", ""),
    ("e34_meas_weight_rel", "e34_meas_weight_addsub", "prerequisite_for", "medium", "printed p. 21; [4수03-21]~[4수03-23]", "단위 관계 이해에서 무게의 덧셈과 뺄셈으로 이어지는 구성", "성취기준 배열 순서에서 추론한 관계다."),
    ("e12_meas_compare_weight", "e34_meas_weight_measure", "prerequisite_for", "medium", "printed p. 14, 21", "무게의 직접 비교에서 표준 단위 측정으로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_geo_angle", "e34_meas_degree", "related_to", "high", "printed p. 21; [4수03-24]", "각의 크기의 단위로 1도를 다룬다", ""),
    ("e34_meas_degree", "e34_meas_protractor", "used_in", "high", "printed p. 21; [4수03-24]", "1도를 알고 각도기로 각의 크기를 측정한다", ""),
    ("e34_meas_protractor", "e34_meas_angle_sum", "used_in", "medium", "printed p. 21; [4수03-24]~[4수03-25]", "각의 크기 측정이 내각 크기의 합 추론에 쓰인다", "성취기준 배열 순서에서 추론한 관계다."),
    ("e34_meas_length_measure", "e34_meas_sense", "used_in", "high", "printed p. 23 적용 시 고려 사항", "재거나 어림하는 측정 활동으로 양감을 기르게 한다", ""),
    ("e12_meas_approx", "e34_meas_length_measure", "used_in", "high", "printed p. 23 적용 시 고려 사항", "눈금에 일치하지 않는 측정값을 '약'으로 표현하게 한다", ""),
    ("e12_meas_standard_need", "e34_meas_capacity_measure", "related_to", "high", "printed p. 23 적용 시 고려 사항", "들이·무게의 표준 단위 도입 전에 표준 단위의 필요성을 알게 한다", ""),
    # 자료와 가능성
    ("e34_data_collect", "e34_data_pictograph_draw", "prerequisite_for", "high", "printed p. 23; [4수04-01]", "자료를 수집하여 그림그래프로 나타낸다는 진술 구조", ""),
    ("e34_data_collect", "e34_data_bar_draw", "prerequisite_for", "high", "printed p. 23; [4수04-01]", "자료를 수집하여 막대그래프로 나타낸다는 진술 구조", ""),
    ("e34_data_collect", "e34_data_line_draw", "prerequisite_for", "high", "printed p. 23; [4수04-02]", "자료를 수집하여 꺾은선그래프로 나타낸다는 진술 구조", ""),
    ("e34_data_pictograph", "e34_data_pictograph_draw", "used_in", "high", "printed p. 23; [4수04-01]", "그림그래프로 나타내고 해석한다", ""),
    ("e34_data_bar", "e34_data_bar_draw", "used_in", "high", "printed p. 23; [4수04-01]", "막대그래프로 나타내고 해석한다", ""),
    ("e34_data_line", "e34_data_line_draw", "used_in", "high", "printed p. 23; [4수04-02]", "꺾은선그래프로 나타내고 해석한다", ""),
    ("e12_data_to_graph", "e34_data_pictograph_draw", "prerequisite_for", "medium", "printed p. 15, 23", "○·×·/ 그래프에서 그림그래프·막대그래프로 확장", "학년군 사이 범위 확장에서 추론한 관계다."),
    ("e34_data_bar_draw", "e34_data_choose_graph", "used_in", "high", "printed p. 23 성취기준 해설", "크기 비교에는 막대그래프가 편리함을 알고 선택하게 한다", ""),
    ("e34_data_line_draw", "e34_data_choose_graph", "used_in", "high", "printed p. 23 성취기준 해설", "변화의 경향에는 꺾은선그래프가 편리함을 알고 선택하게 한다", ""),
    ("e34_data_choose_graph", "e34_data_inquiry", "used_in", "high", "printed p. 23; [4수04-03]", "탐구 과정에서 목적에 맞는 그래프를 선택한다", ""),
    ("e34_data_collect", "e34_data_inquiry", "used_in", "high", "printed p. 23; [4수04-03]", "탐구 문제 해결을 위해 자료를 수집, 정리한다", ""),
    ("e34_data_inquiry", "e34_data_critical", "related_to", "high", "printed p. 24 적용 시 고려 사항", "표현의 적절성을 비판적으로 판단하게 한다", ""),
]
